Repository CEED/libCEED, pull requests merged in 2018-08, with the labels that each got.

#116 Fix typo in tmpl backend init
  backends/template/ceed-tmpl.c
Labels: bug, minor

#122 In tests/tap.sh, remove temporary files when interrupted
  tests/tap.sh
Labels: minor, testing

#121 Add OCCA to Travis CI
  .travis.yml
Labels: OCCA, minor, testing

#136 A few improvements in the makefile
  Makefile
Labels: building

#143 Add testing whitelist
  backends/magma/ceed-magma.c
  backends/occa/ceed-occa-restrict.c
  backends/occa/ceed-occa.c
  backends/occa/ceed-occa.h
  tests/tap.sh
Labels: testing
