Repository CEED/libCEED, pull requests merged in 2018-03, with the labels that each got.

#48 Add CEED_DIR to make-nek-examples.sh
  examples/nek5000/make-nek-examples.sh
Labels: enhancement

#53 install: Add ceedf.h to install
  Makefile
Labels: minor

#55 makefile: only replace CC and FC when they are default (or undefined)
  Makefile
Labels: building

#56 Update the Nek5000 example run process
  examples/nek5000/README.md
  examples/nek5000/bp1.usr
  examples/nek5000/run-nek-example.sh
Labels: examples, frontend

#60 Nek: Update README.md
  README.md
Labels: documentation

#62 [occa] Updated verbose flag
  backends/occa/ceed-occa.c
Labels: backend, minor
