Repository CEED/libCEED, pull requests merged in 2019-09, with the labels that each got.

#331 PETSc - Minor tidying
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, PETSc, minor

#332 Update NS example documentation
  examples/navier-stokes/common.h
  examples/navier-stokes/densitycurrent.h
Labels: documentation

#334 Work around LIBXSMM bug
  .travis.yml
Labels: 1-In Review, LIBXSMM, bug, testing

#335 Homogenize examples by using ncomp and dim
  examples/ceed/ex1.c
  examples/mfem/bp1.hpp
  examples/mfem/bp3.hpp
  examples/navier-stokes/navierstokes.c
  examples/nek/bps/bps.usr
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, enhancement, examples

#336 CUDA - Rename SyncState -> CeedCudaSyncState
  backends/cuda/ceed-cuda-vec.c
  backends/cuda/ceed-cuda.h
Labels: 1-In Review, CUDA, minor

#338 Add CeedPragmaOMP to bps
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda/ceed-cuda-qfunction-load.cpp
  examples/ceed/ex1.h
  examples/mfem/bp1.h
  examples/mfem/bp3.h
  examples/navier-stokes/advection.h
  examples/navier-stokes/common.h
  examples/navier-stokes/densitycurrent.h
  examples/nek/bps/bps.h
  examples/nek/bps/bps.usr
  examples/petsc/bp1.h
  examples/petsc/bp2.h
  examples/petsc/bp3.h
  examples/petsc/bp4.h
  include/ceed.h
Labels: 1-In Review, Nek5000, PETSc, enhancement, examples

#342 Make examples consistent
  examples/ceed/ex1.c
  examples/ceed/ex1.h
  examples/ceed/ex2.h
  examples/mfem/bp1.h
  examples/mfem/bp1.hpp
  examples/mfem/bp3.h
  examples/mfem/bp3.hpp
  examples/navier-stokes/common.h
  examples/nek/bps/bps.h
  examples/nek/bps/bps.usr
  examples/petsc/bp1.h
  examples/petsc/bp2.h
  examples/petsc/bp3.h
  examples/petsc/bp4.h
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, examples

#343 QFunction - document absolute path requirement
  interface/ceed-qfunction.c
Labels: 1-In Review, documentation, minor

#344 Fortran - Use preprocessor directive to provide abs path to true qfuntion source
  Makefile
  examples/nek/bps/bps.usr
  examples/nek/nek-examples.sh
  tests/t400-qfunction-f.f90
  tests/t400-qfunction-f.h
  tests/t400-qfunction-f.okl
  tests/t401-qfunction-f.f90
  tests/t401-qfunction-f.h
  tests/t401-qfunction-f.okl
  tests/t500-operator-f.f90
  tests/t500-operator-f.h
  tests/t500-operator-f.okl
  tests/t501-operator-f.f90
  tests/t501-operator-f.h
  tests/t501-operator-f.okl
  tests/t502-operator-f.f90
  tests/t502-operator-f.h
  tests/t502-operator-f.okl
  tests/t510-operator-f.f90
  tests/t510-operator-f.h
  tests/t510-operator-f.okl
  tests/t511-operator-f.f90
  tests/t511-operator-f.h
  tests/t511-operator-f.okl
  tests/t520-operator-f.f90
  tests/t520-operator-f.h
  tests/t520-operator-f.okl
  tests/t521-operator-f.f90
  tests/t521-operator-f.h
  tests/t521-operator-f.okl
Labels: 1-In Review, bug, building, fortran, minor

#341 Improved performance of cuda-gen backend
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda-shared/ceed-cuda-shared.h
  backends/cuda/ceed-cuda-basis.c
  backends/cuda/ceed-cuda-restriction.c
  backends/cuda/ceed-cuda.h
  examples/mfem/bp1.hpp
  examples/mfem/bp3.hpp
Labels: 1-In Review, CUDA, GPU, backend, enhancement

#346 MFEM - revert make style error
  examples/mfem/bp1.hpp
  examples/mfem/bp3.hpp
Labels: 1-In Review, bug, minor

#355 Tests - Fix colo typo in tests
  tests/output/t302-basis-f.out
  tests/output/t302-basis.out
  tests/t302-basis-f.f90
  tests/t302-basis.c
Labels: 1-In Review, bug, minor, testing

#356 Codecov Exceptions
  backends/avx/ceed-avx-blocked.c
  backends/avx/ceed-avx-serial.c
  backends/blocked/ceed-blocked-operator.c
  backends/blocked/ceed-blocked.c
  backends/memcheck/ceed-memcheck.c
  backends/opt/ceed-opt-blocked.c
  backends/opt/ceed-opt-operator.c
  backends/opt/ceed-opt-serial.c
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref-restriction.c
  backends/ref/ceed-ref-vec.c
  backends/ref/ceed-ref.c
  backends/template/ceed-tmpl-sub.c
  backends/template/ceed-tmpl.c
  backends/xsmm/ceed-xsmm-blocked.c
  backends/xsmm/ceed-xsmm-serial.c
  backends/xsmm/ceed-xsmm-tensor.c
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-tensor.c
  interface/ceed-vec.c
  interface/ceed.c
  tests/t304-basis-f.f90
  tests/t305-basis-f.f90
  tests/t315-basis-f.f90
  tests/t315-basis.c
  tests/t316-basis.c
Labels: 1-In Review, documentation, enhancement, minor, testing

#358 XSMM - drop unused tensor contract fallback when C != 1
  backends/xsmm/ceed-xsmm-tensor.c
Labels: 1-In Review, CPU, LIBXSMM, minor

#353 Makefile - Detect MKLROOT for LIBXSMM linking
  Makefile
  README.md
Labels: 1-In Review, LIBXSMM, building

#361 Style - minor typo fix
  examples/petsc/bpsdmplex.c
  interface/ceed-operator.c
Labels: 1-In Review, bug, minor

#362 Revert 1d5e3c8
  tests/README.md
Labels: 1-In Review, bug, minor

#364 PETSc - add MPI_Reduce and PetscBarrier for benchmarking
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, PETSc, bug

#365 PETSc - Fix MPI_Allreduce warning w/ierr check
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, PETSc, bug, minor

#366 Travis - Update to PETSc 3.12.0
  .travis.yml
Labels: 1-In Review, PETSc, minor
