Repository CEED/libCEED, pull requests merged in 2019-12, with the labels that each got.

#423 Small fixes from Python Work
  backends/occa/ceed-occa-qfunction-noop.c
  include/ceed-fortran-name.h
  include/ceed.h
  include/ceedf.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed.c
  tests/output/t203-elemrestriction-f.out
  tests/output/t402-qfunction-f.out
  tests/output/t402-qfunction.out
  tests/t001-ceed.c
  tests/t303-basis.c
  tests/t310-basis.c
  tests/t311-basis.c
  tests/t312-basis.c
  tests/t313-basis.c
  tests/t314-basis.c
  tests/t320-basis-f.h
  tests/t320-basis.h
  tests/t321-basis.c
  tests/t322-basis.c
  tests/t323-basis.c
  tests/t324-basis.c
  tests/t325-basis.c
  tests/t400-qfunction-f.f90
  tests/t400-qfunction.c
  tests/t401-qfunction-f.f90
  tests/t401-qfunction.c
  tests/t402-qfunction-f.f90
  tests/t402-qfunction.c
  tests/t500-operator.c
  tests/t510-operator.c
  tests/t511-operator.c
  tests/t520-operator.c
  tests/t521-operator.c
  tests/t522-operator.c
  tests/t523-operator.c
Labels: 1-In Review, minor

#399 Restriction Optimizations
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/ref/ceed-ref-restriction.c
  include/ceed.h
  interface/ceed-operator.c
Labels: 1-In Review, CPU, backend, performance

#428 Small doc fixes
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-qfunction.c
Labels: 1-In Review, documentation

#432 Minor Renaming for Consistency
  backends/cuda/ceed-cuda-vector.c
  backends/cuda/cuda-vector.cu
  backends/ref/ceed-ref-vector.c
  include/ceed.h
  interface/ceed-vector.c
  tests/output/t107-vector-f.out
  tests/output/t107-vector.out
  tests/t100-vector-f.f90
  tests/t100-vector.c
  tests/t101-vector-f.f90
  tests/t101-vector.c
  tests/t102-vector-f.f90
  tests/t102-vector.c
  tests/t103-vector-f.f90
  tests/t103-vector.c
  tests/t104-vector-f.f90
  tests/t104-vector.c
  tests/t105-vector-f.f90
  tests/t105-vector.c
  tests/t106-vector-f.f90
  tests/t106-vector.c
  tests/t107-vector-f.f90
  tests/t107-vector.c
  tests/t110-vector.c
  tests/t111-vector.c
  tests/t112-vector.c
  tests/t113-vector.c
  tests/t114-vector.c
  tests/t115-vector.c
  tests/t116-vector.c
  tests/t117-vector.c
  tests/t118-vector.c
Labels: 1-In Review, minor

#433 Fix missing free in ex2
  examples/ceed/ex2.c
Labels: 1-In Review, bug, examples, minor

#431 Operator - move AssembleDiagonal to fallback
  backends/avx/ceed-avx-blocked.c
  backends/avx/ceed-avx-serial.c
  backends/avx/ceed-avx-tensor.c
  backends/blocked/ceed-blocked-operator.c
  backends/blocked/ceed-blocked.c
  backends/memcheck/ceed-memcheck-blocked.c
  backends/memcheck/ceed-memcheck-qfunction.c
  backends/memcheck/ceed-memcheck-serial.c
  backends/occa/ceed-occa-basis.c
  backends/opt/ceed-opt-blocked.c
  backends/opt/ceed-opt-operator.c
  backends/opt/ceed-opt-serial.c
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref-qfunction.c
  backends/ref/ceed-ref-restriction.c
  backends/ref/ceed-ref-tensor.c
  backends/ref/ceed-ref-vector.c
  backends/ref/ceed-ref.c
  backends/template/ceed-tmpl-sub.c
  backends/template/ceed-tmpl.c
  backends/xsmm/ceed-xsmm-blocked.c
  backends/xsmm/ceed-xsmm-serial.c
  backends/xsmm/ceed-xsmm-tensor.c
  examples/petsc/multigrid.c
  include/ceed-backend.h
  include/ceed-impl.h
  interface/ceed-basis.c
  interface/ceed-operator.c
  interface/ceed.c
Labels: 1-In Review, backend, enhancement, performance

#434 XSMM - release JiT kernels
  backends/xsmm/ceed-xsmm-tensor.c
Labels: 1-In Review, CPU, LIBXSMM, minor
