Repository CEED/libCEED, pull requests merged in 2019-08, with the labels that each got.

#303 In Makefile, use the user defined c++ compiler as the nvcc host compiler
  Makefile
Labels: CUDA, building, minor

#308 Makefile: Fix make clean for examples
  examples/Makefile
Labels: 1-In Review, bug, building, minor

#309 Fix a bug in the description of vectorial bps in petsc examples
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, PETSc, bug, examples

#310 Fix atomicAdd in cuda-gen backend
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
Labels: 1-In Review, CUDA, backend, bug, minor

#317 Add *.bin* files to NS clean and gitignore
  examples/navier-stokes/.gitignore
  examples/navier-stokes/Makefile
Labels: 1-In Review, minor

#319 In Navier-Stokes use BasisGetNumNodes
  examples/navier-stokes/navierstokes.c
Labels: 1-In Review, minor

#318 Update sign in advection example
  examples/navier-stokes/advection.h
  examples/navier-stokes/common.h
  examples/navier-stokes/densitycurrent.h
Labels: 1-In Review, minor

#326 PETSc - Fix -local description
  examples/petsc/bps.c
Labels: 1-In Review, PETSc, minor

#324 Doc - Add CUDA-Gen to Doxygen
  Doxyfile
Labels: 1-In Review, documentation, minor

#327 PETSc - DMGetDefaultSection is depricated
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, PETSc, minor

#290 Add Grad w/collo Interp mode to CPU backends
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref.h
  tests/t309-basis-f.f90
  tests/t309-basis.c
Labels: 1-In Review, CPU, enhancement, minor, performance

#330 PETSc - minor bpsdmplex fixes
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, PETSc, minor

#329 Fix QFunction Ncomp vs Size
  backends/blocked/ceed-blocked-operator.c
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-qfunction-load.cpp
  backends/cuda/ceed-cuda-qfunction.c
  backends/occa/ceed-occa-operator.c
  backends/occa/ceed-occa-qfunction-noop.c
  backends/occa/ceed-occa-qfunction-op.c
  backends/occa/ceed-occa-qfunction.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-operator.c
  doc/libCEEDapi.md
  examples/ceed/ex1.c
  examples/mfem/bp1.hpp
  examples/mfem/bp3.hpp
  examples/nek/bps/bps.usr
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-basis.c
  interface/ceed-qfunction.c
  tests/t500-operator-f.f90
  tests/t500-operator.c
  tests/t501-operator-f.f90
  tests/t501-operator.c
  tests/t502-operator-f.f90
  tests/t502-operator.c
  tests/t510-operator-f.f90
  tests/t510-operator.c
  tests/t511-operator-f.f90
  tests/t511-operator.c
  tests/t520-operator-f.f90
  tests/t520-operator.c
  tests/t521-operator-f.f90
  tests/t521-operator.c
Labels: 1-In Review, CPU, CUDA, OCCA, documentation, frontend

#323 NS: clean geometric factors
  examples/navier-stokes/advection.h
  examples/navier-stokes/common.h
  examples/navier-stokes/densitycurrent.h
  examples/navier-stokes/navierstokes.c
Labels: 1-In Review, bug, enhancement, examples

#328 Ref - remove dead code from basis collo grad
  backends/ref/ceed-ref-basis.c
Labels: 1-In Review, bug, minor
