Repository CEED/libCEED, pull requests merged in 2019-03, with the labels that each got.

#204 Fix Stray File (Issue #200)
  Makefile
Labels: 1-In Review, bug, building, minor

#208 CeedBasisApply check
  interface/ceed-basis.c
  tests/t308-basis.c
  tests/t310-basis.c
  tests/tap.sh
Labels: 1-In Review, bug, frontend

#209 Make Style Updates
  Makefile
  backends/avx/ceed-avx-basis.c
  backends/avx/ceed-avx.h
  backends/blocked/ceed-blocked-basis.c
  backends/blocked/ceed-blocked-operator.c
  backends/blocked/ceed-blocked.h
  backends/occa/ceed-occa-basis.c
  backends/occa/ceed-occa-okl.c
  backends/occa/ceed-occa-operator.c
  backends/occa/ceed-occa-qfunction-noop.c
  backends/occa/ceed-occa-qfunction-op.c
  backends/occa/ceed-occa-qfunction.c
  backends/occa/ceed-occa-restrict.c
  backends/occa/ceed-occa-vector.c
  backends/occa/ceed-occa.h
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref-qfunction.c
  backends/ref/ceed-ref-restriction.c
  backends/ref/ceed-ref-vec.c
  backends/ref/ceed-ref.h
  backends/xsmm/ceed-xsmm-basis.c
  backends/xsmm/ceed-xsmm-blocked.c
  backends/xsmm/ceed-xsmm-serial.c
  backends/xsmm/ceed-xsmm.h
  examples/ceed/ex1.c
  examples/mfem/bp1.cpp
  examples/mfem/bp1.hpp
  examples/mfem/bp3.cpp
  examples/mfem/bp3.hpp
  examples/petsc/bp1.c
  examples/petsc/bp3.c
  examples/petsc/bp3.h
  include/ceed-backend.h
  include/ceed.h
  interface/ceed-basis.c
  interface/ceed-fortran.c
  interface/ceed-qfunction.c
  interface/ceed.c
Labels: 1-In Review, bug, building, minor

#197 Operator Composition
  backends/blocked/ceed-blocked-operator.c
  backends/blocked/ceed-blocked.h
  backends/magma/ceed-magma.c
  backends/magma/magma_dtensor_contract.c
  backends/occa/ceed-occa-operator.c
  backends/occa/ceed-occa.c
  backends/occa/ceed-occa.h
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref.c
  backends/ref/ceed-ref.h
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed.c
  tests/t500-operator-f.f90
  tests/t500-operator.c
  tests/t501-operator-f.f90
  tests/t501-operator.c
  tests/t502-operator-f.f90
  tests/t502-operator.c
  tests/t510-operator-f.f90
  tests/t510-operator.c
  tests/t511-operator-f.f90
  tests/t511-operator.c
  tests/t520-operator-f.f90
  tests/t520-operator-f.okl
  tests/t520-operator.c
  tests/t520-operator.okl
  tests/t521-operator-f.f90
  tests/t521-operator-f.okl
  tests/t521-operator.c
  tests/t521-operator.okl
Labels: 1-In Review, CPU, design, enhancement, frontend

#211 Add CeedTensorContract object
  backends/avx/ceed-avx-basis.c
  backends/avx/ceed-avx-blocked.c
  backends/avx/ceed-avx-serial.c
  backends/avx/ceed-avx-tensor.c
  backends/avx/ceed-avx.h
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-tensor.c
  backends/ref/ceed-ref.c
  backends/ref/ceed-ref.h
  backends/xsmm/ceed-xsmm-basis.c
  backends/xsmm/ceed-xsmm-blocked.c
  backends/xsmm/ceed-xsmm-serial.c
  backends/xsmm/ceed-xsmm-tensor.c
  backends/xsmm/ceed-xsmm.h
  include/ceed-backend.h
  include/ceed-impl.h
  interface/ceed-basis.c
  interface/ceed-tensor.c
  interface/ceed.c
Labels: 1-In Review, CPU, backend, design, enhancement

#210 Drop array argument from backend RestoreArray
  backends/cuda/ceed-cuda-vec.c
  backends/magma/ceed-magma.c
  backends/occa/ceed-occa-vector.c
  backends/ref/ceed-ref-vec.c
  include/ceed-impl.h
  interface/ceed-vec.c
Labels: 1-In Review, backend, frontend, minor

#195 Simple Cuda backend using one thread per element
  Makefile
  README.md
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda-reg/ceed-cuda-reg.c
  backends/cuda-reg/ceed-cuda-reg.h
  backends/cuda-reg/cuda-reg-basis.cu
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda.c
  backends/cuda/ceed-cuda.h
  tests/t401-qfunction-f.cu
  tests/t401-qfunction.cu
Labels: 1-In Review, CUDA, GPU, backend

#214 Add CeedVectorSyncArray
  examples/mfem/bp1.hpp
  examples/mfem/bp3.hpp
  examples/nek5000/bp1.usr
  examples/nek5000/bp3.usr
  examples/petsc/bp1.c
  examples/petsc/bp3.c
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed-vec.c
Labels: 1-In Review, enhancement, frontend

#215 Small clang-tidy fixes
  backends/blocked/ceed-blocked-operator.c
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref-vec.c
  interface/ceed-elemrestriction.c
  interface/ceed-vec.c
Labels: 1-In Review, bug, minor

#218 Add Jenkinsfile
  .kubernetes-pod.yaml
  Jenkinsfile
  Makefile
  azure-pipelines.yml
  examples/petsc/bp1.c
  examples/petsc/bp3.c
  tests/junit.py
Labels: 1-In Review

#220 README typo fix
  README.md
Labels: 1-In Review, minor

#152 Explicit time stepping NS solver
  Doxyfile
  Makefile
  examples/.gitignore
  examples/Makefile
  examples/README.md
  examples/ceed/.gitignore
  examples/navier-stokes/.gitignore
  examples/navier-stokes/Makefile
  examples/navier-stokes/README.md
  examples/navier-stokes/advection.h
  examples/navier-stokes/common.h
  examples/navier-stokes/densitycurrent.h
  examples/navier-stokes/navierstokes.c
Labels: 1-In Review, PETSc, examples, frontend

#221 Update Nek BP3 file description
  examples/nek5000/bp3.usr
Labels: 1-In Review, minor

#222 Add MKL optional flag
  Makefile
  README.md
Labels: 1-In Review, LIBXSMM, bug, building, minor

#223 Strcpy fix
  examples/navier-stokes/navierstokes.c
  interface/ceed-qfunction.c
  interface/ceed.c
Labels: 1-In Review, bug, minor

#225 Add CeedGetPreferredMemType
  backends/cuda/ceed-cuda.c
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed.c
  tests/t000-ceed-f.f90
  tests/t000-ceed.c
  tests/t001-ceed-f.f90
  tests/t001-ceed.c
Labels: 1-In Review, CPU, GPU, frontend, minor

#226 Ns fix alignment
  README.md
  examples/navier-stokes/navierstokes.c
  examples/petsc/.gitignore
Labels: minor

#227 Add atomicAdd in /cuda/ref backend for compute capability < 6.0
  backends/cuda/ceed-cuda-restriction.c
Labels: 1-In Review, CUDA, GPU, backend, building, enhancement

#230 Fix the output of 'make info' for the CUDA backends.
  Makefile
Labels: minor
