Repository CEED/libCEED, pull requests merged in 2019-11, with the labels that each got.

#411 Reduce Number of Fortran tests
  tests/t001-ceed.c
  tests/t110-vec-f.f90
  tests/t111-vec-f.f90
  tests/t112-vec-f.f90
  tests/t113-vec-f.f90
  tests/t114-vec-f.f90
  tests/t115-vec-f.f90
  tests/t116-vec-f.f90
  tests/t117-vec-f.f90
  tests/t118-vec-f.f90
  tests/t203-elemrestriction-f.f90
  tests/t204-elemrestriction-f.f90
  tests/t205-elemrestriction-f.f90
  tests/t206-elemrestriction-f.f90
  tests/t207-elemrestriction-f.f90
  tests/t303-basis-f.f90
  tests/t310-basis-f.f90
  tests/t311-basis-f.f90
  tests/t312-basis-f.f90
  tests/t315-basis-f.f90
  tests/t316-basis-f.f90
  tests/t321-basis-f.f90
  tests/t324-basis-f.f90
  tests/t325-basis-f.f90
Labels: 1-In Review, fortran, minor, testing

#402 Makefile - move --no-as-needed
  Makefile
Labels: 1-In Review, bug, building

#405 Fix Style Indentation Errors
  Makefile
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda/ceed-cuda-basis.c
  backends/cuda/ceed-cuda-restriction.c
  backends/magma/ceed-magma.h
  backends/memcheck/ceed-memcheck-qfunction.c
  backends/ref/ceed-ref-qfunction.c
  examples/ceed/ex2.h
  examples/mfem/bp1.hpp
  examples/mfem/bp3.hpp
  examples/navier-stokes/advection.h
  examples/navier-stokes/common.h
  examples/navier-stokes/densitycurrent.h
  examples/navier-stokes/navierstokes.c
  examples/petsc/area.c
  examples/petsc/bps.c
  examples/petsc/multigrid.c
  examples/petsc/setup.h
  gallery/poisson2d/ceed-poisson2dapply.h
  gallery/poisson3d/ceed-poisson3dapply.h
  include/ceed-backend.h
  interface/ceed-qfunction.c
  interface/ceed.c
  tests/t324-basis.c
  tests/t325-basis.c
  tests/t522-operator.h
Labels: 1-In Review, minor

#409 CPU - avoid extra memcpy for identity qfunctions
  backends/blocked/ceed-blocked-operator.c
  backends/blocked/ceed-blocked.h
  backends/opt/ceed-opt-operator.c
  backends/opt/ceed-opt.h
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref.h
  examples/petsc/multigrid.c
  examples/petsc/qfunctions/bps/identity.h
  examples/petsc/qfunctions/bps/identity.okl
  examples/petsc/setup.h
  gallery/identity/ceed-identity.c
  include/ceed-backend.h
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed-qfunction.c
  interface/ceed-vec.c
  tests/t411-qfunction-f.f90
  tests/t411-qfunction.c
  tests/t412-qfunction-f.f90
  tests/t412-qfunction.c
  tests/tap.sh
Labels: 1-In Review, CPU, performance

#415 Tests - add t106 SyncArray and t107 VectorView
  tests/output/t107-vec-f.out
  tests/output/t107-vec.out
  tests/t105-vec.c
  tests/t106-vec-f.f90
  tests/t106-vec.c
  tests/t107-vec-f.f90
  tests/t107-vec.c
Labels: 1-In Review, GPU, minor, testing

#416 Fix t301-basis.c
  interface/ceed-basis.c
  interface/ceed-python/ceed_basis.py
  tests/t301-basis.c
Labels: 1-In Review, bug, testing

#418 Serial Memcheck Backend
  Makefile
  README.md
  backends/memcheck/ceed-memcheck-blocked.c
  backends/memcheck/ceed-memcheck-serial.c
  interface/ceed-python/ceed_basis.py
Labels: 1-In Review, minor, testing

#420 revert typo
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
Labels: 1-In Review, bug, minor

#419 QFunction - add QFunctionView
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-types.c
  tests/output/t402-qfunction-f.out
  tests/output/t402-qfunction.out
  tests/output/t413-qfunction-f.out
  tests/output/t413-qfunction.out
  tests/output/t504-operator-f.out
  tests/output/t504-operator.out
  tests/output/t523-operator-f.out
  tests/output/t523-operator.out
  tests/t402-qfunction-f.f90
  tests/t402-qfunction.c
  tests/t413-qfunction-f.f90
  tests/t413-qfunction.c
  tests/t504-operator-f.f90
  tests/t504-operator.c
  tests/t523-operator-f.f90
  tests/t523-operator.c
Labels: 1-In Review, design, minor

#406 Delegate AssembleLinearQF to ref/serial when not impl
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda/ceed-cuda-operator.c
  backends/occa/ceed-occa-operator.c
  backends/occa/ceed-occa-restrict.okl
  backends/ref/ceed-ref-operator.c
  include/ceed-backend.h
  include/ceed-impl.h
  interface/ceed-operator.c
  interface/ceed.c
  tests/t532-operator.h
  tests/t532-operator.okl
  tests/t534-operator-f.f90
Labels: 1-In Review, CPU, GPU, backend
