Repository CEED/libCEED, pull requests merged in 2019-07, with the labels that each got.

#289 Update CUDA/OCCA CEED_COPY_VALUES logic
  backends/cuda/ceed-cuda-vec.c
  backends/occa/ceed-occa-vector.c
Labels: 1-In Review, CUDA, OCCA, bug, minor

#291 Add ElemRestrGetMultiplicity and Tests
  include/ceed.h
  interface/ceed-elemrestriction.c
  interface/ceed-fortran.c
  tests/t209-elemrestriction-f.f90
  tests/t209-elemrestriction.c
Labels: 1-In Review, frontend, minor

#295 BugFix - Resource strcmp in LIBXSMM backends
  backends/avx/ceed-avx-blocked.c
  backends/avx/ceed-avx-serial.c
  backends/blocked/ceed-blocked.c
  backends/memcheck/ceed-memcheck.c
  backends/opt/ceed-opt-blocked.c
  backends/opt/ceed-opt-serial.c
  backends/ref/ceed-ref.c
  backends/template/ceed-tmpl-sub.c
  backends/template/ceed-tmpl.c
  backends/xsmm/ceed-xsmm-blocked.c
  backends/xsmm/ceed-xsmm-serial.c
Labels: 1-In Review, CPU, LIBXSMM, bug, minor

#292 Fix NS bug
  examples/navier-stokes/densitycurrent.h
Labels: 1-In Review, bug, examples

#297 Fix typo in t209-f
  tests/t209-elemrestriction-f.f90
Labels: 1-In Review, bug, minor, testing

#298 Fix ref backend priorities
  backends/blocked/ceed-blocked.c
  backends/ref/ceed-ref.c
Labels: 1-In Review, CPU, bug, minor

#241 Update nek5000 example scripts
  .travis.yml
  Makefile
  examples/Makefile
  examples/README.md
  examples/nek/.gitignore
  examples/nek/Makefile
  examples/nek/README.md
  examples/nek/SIZE.in
  examples/nek/boxes/b.box
  examples/nek/boxes/b1e.rea
  examples/nek/bps/bps.cu
  examples/nek/bps/bps.okl
  examples/nek/bps/bps.usr
  examples/nek/nek-examples.sh
  examples/nek5000/.gitignore
  examples/nek5000/bp1.cu
  examples/nek5000/bp1.okl
  examples/nek5000/bp3.usr
  examples/nek5000/generate-boxes.sh
  examples/nek5000/make-nek-examples.sh
  examples/nek5000/run-nek-example.sh
  tests/junit.py
  tests/tap.sh
Labels: 1-In Review

#300 README: Update corectness for examples
  README.md
  examples/README.md
Labels: 1-In Review, documentation, minor

#275 Full jit compiled operator: cuda-gen backend
  Makefile
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator-build.h
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda/ceed-cuda.h
  examples/ceed/ex1.qf
  examples/mfem/bp1.qf
  examples/mfem/bp3.qf
  examples/nek5000/bp1.qf
  examples/nek5000/bp3.qf
  examples/petsc/bp1.qf
  examples/petsc/bp2.qf
  examples/petsc/bp3.qf
  examples/petsc/bp4.qf
  examples/petsc/bps.c
  examples/petsc/common.qf
  include/ceed-backend.h
  tests/t400-qfunction-f.qf
  tests/t400-qfunction.qf
  tests/t401-qfunction-f.qf
  tests/t401-qfunction.qf
  tests/t500-operator-f.qf
  tests/t500-operator.qf
  tests/t501-operator-f.qf
  tests/t501-operator.qf
  tests/t502-operator-f.qf
  tests/t502-operator.qf
  tests/t510-operator-f.qf
  tests/t510-operator.qf
  tests/t511-operator-f.qf
  tests/t511-operator.qf
  tests/t520-operator-f.qf
  tests/t520-operator.qf
  tests/t521-operator-f.qf
  tests/t521-operator.qf
Labels: 1-In Review, CUDA, GPU, backend, performance

#301 Nek: move bps qf files
  examples/nek/bps/bps.qf
  examples/nek5000/bp1.qf
Labels: 1-In Review, CUDA, Nek5000, bug, minor
