Repository CEED/libCEED, pull requests merged in 2019-10, with the labels that each got.

#369 QFunction - Fix identity qfunction field size
  interface/ceed-qfunction.c
Labels: 1-In Review, CUDA, bug, minor

#111 Magma dev optimizations
  Makefile
  backends/magma/atomics.cuh
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma.c
  backends/magma/ceed-magma.h
  backends/magma/gccm.py
  backends/magma/magma_check_cudaerror.h
  backends/magma/magma_dbasisApply_grad.cu
  backends/magma/magma_dbasisApply_grad_device.cuh
  backends/magma/magma_dbasisApply_interp.cu
  backends/magma/magma_dbasisApply_interp_device.cuh
  backends/magma/magma_dbasisApply_weight.cu
  backends/magma/magma_devptr.cu
  backends/magma/magma_dtensor_contract.c
  backends/magma/magma_tc_device.cuh
Labels: 1-In Review, GPU, MAGMA, backend

#371 Minor MAGMA Updates
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma.h
  backends/magma/magma_dtensor_contract.c
Labels: 1-In Review, GPU, MAGMA, minor

#373 Add refcounts for Operator field components
  interface/ceed-operator.c
Labels: 1-In Review, design, enhancement, minor

#306 Assemble Linear QFunction
  backends/blocked/ceed-blocked-operator.c
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda/ceed-cuda-operator.c
  backends/occa/ceed-occa-operator.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-operator.c
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-tensor.c
  interface/ceed-vec.c
  interface/ceed.c
  tests/README.md
  tests/t530-operator-f.f90
  tests/t530-operator.c
  tests/t530-operator.h
  tests/t530-operator.okl
  tests/t531-operator-f.f90
  tests/t531-operator.c
  tests/t531-operator.h
  tests/t531-operator.okl
  tests/t532-operator-f.f90
  tests/t532-operator.c
  tests/t532-operator.h
  tests/t532-operator.okl
Labels: 1-In Review, CPU, enhancement, performance

#379 CPU - Use work vectors for AssembleLinearQF
  backends/blocked/ceed-blocked-operator.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-operator.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
Labels: 1-In Review, CPU, enhancement, minor

#273 P Multigrid Example
  backends/blocked/ceed-blocked-operator.c
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda/ceed-cuda-basis.c
  backends/cuda/ceed-cuda-restriction.c
  backends/magma/ceed-magma.h
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-operator.c
  backends/xsmm/ceed-xsmm-tensor.c
  examples/ceed/ex1.h
  examples/ceed/ex2.h
  examples/mfem/bp1.h
  examples/navier-stokes/advection.h
  examples/navier-stokes/densitycurrent.h
  examples/navier-stokes/navierstokes.c
  examples/petsc/Makefile
  examples/petsc/README.md
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
  examples/petsc/meshes/3Dbrick.exo
  examples/petsc/meshes/3Dbrick4els.exo
  examples/petsc/multigrid.c
  examples/petsc/qfunctions/bp1.h
  examples/petsc/qfunctions/bp1.okl
  examples/petsc/qfunctions/bp2.h
  examples/petsc/qfunctions/bp2.okl
  examples/petsc/qfunctions/bp3.h
  examples/petsc/qfunctions/bp3.okl
  examples/petsc/qfunctions/bp4.h
  examples/petsc/qfunctions/bp4.okl
  examples/petsc/qfunctions/common.h
  examples/petsc/qfunctions/common.okl
  examples/petsc/qfunctions/identity.h
  examples/petsc/qfunctions/identity.okl
  examples/petsc/setup.h
  gallery/identity/ceed-identity.c
  include/ceed-backend.h
  include/ceed.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed.c
  tests/t304-basis.c
  tests/t305-basis.c
  tests/t315-basis.c
  tests/t530-operator.c
  tests/t531-operator.c
  tests/t531-operator.h
  tests/t532-operator.c
Labels: 1-In Review, PETSc, examples

#384 Fix Bug in CPU Collocated Basis Grad
  backends/ref/ceed-ref-basis.c
  examples/petsc/bpsdmplex.c
Labels: 1-In Review, CPU, bug

#383 Facilitate Empty Operators
  include/ceed-impl.h
  interface/ceed-operator.c
Labels: 1-In Review, design, enhancement

#387 PETSc Examples - small fixes
  examples/petsc/bpsdmplex.c
  examples/petsc/multigrid.c
  examples/petsc/setup.h
Labels: 1-In Review, minor

#385 Azure - use junit realsearch=%
  azure-pipelines.yml
Labels: 1-In Review, minor, testing

#388 Move Op/Qf fields to ceed-backend.h
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-operator.c
Labels: 1-In Review, minor

#386 Minor AVX Backend Changes
  backends/avx/ceed-avx-tensor.c
  examples/petsc/bps.c
  examples/petsc/qfunctions/bp2.h
Labels: 1-In Review, CPU, minor

#389 Doc - small fixes
  interface/ceed-elemrestriction.c
  interface/ceed-qfunction.c
Labels: 1-In Review, documentation, minor

#391 Codecov - cover gallery
  .codecov.yml
  .travis.yml
  gallery/identity/ceed-identity.c
  gallery/mass1d/ceed-mass1dbuild.c
  gallery/mass1d/ceed-massapply.c
  gallery/mass2d/ceed-mass2dbuild.c
  gallery/mass3d/ceed-mass3dbuild.c
  gallery/poisson1d/ceed-poisson1dapply.c
  gallery/poisson1d/ceed-poisson1dbuild.c
  gallery/poisson2d/ceed-poisson2dapply.c
  gallery/poisson2d/ceed-poisson2dbuild.c
  gallery/poisson3d/ceed-poisson3dapply.c
  gallery/poisson3d/ceed-poisson3dbuild.c
Labels: 1-In Review, minor, testing

#392 Get Full Ceed Resource Name
  backends/memcheck/ceed-memcheck-qfunction.c
  backends/ref/ceed-ref-qfunction.c
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
  examples/petsc/multigrid.c
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-tensor.c
  interface/ceed-vec.c
  interface/ceed.c
  tests/t002-ceed.c
Labels: 1-In Review, design, minor

#393 Doc - small fixes
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
Labels: 1-In Review, minor

#397 Travis - COVERAGE=1 only for linux
  .travis.yml
Labels: 1-In Review, bug, testing

#394 Add PETSc example areaplex
  benchmarks/README.md
  benchmarks/benchmark.sh
  benchmarks/petsc-bpsraw.sh
  examples/README.md
  examples/petsc/.gitignore
  examples/petsc/Makefile
  examples/petsc/README.md
  examples/petsc/area.c
  examples/petsc/bps.c
  examples/petsc/bpsdmplex.c
  examples/petsc/bpsraw.c
  examples/petsc/multigrid.c
  examples/petsc/qfunctions/area/area.h
  examples/petsc/qfunctions/area/area.okl
  examples/petsc/qfunctions/bps/bp1.h
  examples/petsc/qfunctions/bps/bp1.okl
  examples/petsc/qfunctions/bps/bp2.h
  examples/petsc/qfunctions/bps/bp2.okl
  examples/petsc/qfunctions/bps/bp3.h
  examples/petsc/qfunctions/bps/bp3.okl
  examples/petsc/qfunctions/bps/bp4.h
  examples/petsc/qfunctions/bps/bp4.okl
  examples/petsc/qfunctions/bps/common.h
  examples/petsc/qfunctions/bps/common.okl
  examples/petsc/qfunctions/bps/identity.h
  examples/petsc/qfunctions/bps/identity.okl
  examples/petsc/setup.h
Labels: 1-In Review, CPU, PETSc, examples

#398 Travis - use XSMM v1.14
  .travis.yml
Labels: 1-In Review, CI, CPU, LIBXSMM, minor, testing

#400 Some cleaning
  examples/ceed/ex1.c
  examples/navier-stokes/navierstokes.c
  examples/petsc/.gitignore
  examples/petsc/Makefile
  examples/petsc/bpsraw.c
  examples/petsc/multigrid.c
  examples/petsc/setup.h
  interface/ceed-basis.c
Labels: 1-In Review, enhancement, minor

#401 Makefile - fix small MKL linking error
  Makefile
Labels: 1-In Review, building, minor

#403 Tests - relax t412 tolerence and small style changes
  tests/t411-qfunction.c
  tests/t412-qfunction-f.f90
  tests/t412-qfunction.c
  tests/t530-operator.c
  tests/t531-operator.c
  tests/t532-operator.c
  tests/t533-operator.c
  tests/t534-operator.c
  tests/t535-operator.c
  tests/t536-operator.c
Labels: 1-In Review, minor, testing

#404 Update examples/petsc/.gitignore
  examples/petsc/.gitignore
Labels: 1-In Review, minor

#407 Travis - use xcode11.2
  .travis.yml
Labels: 1-In Review, CI, minor
