Repository CEED/libCEED, pull requests merged in 2019-04, with the labels that each got.

#233 Get rid of sed substitutions
  examples/nek5000/make-nek-examples.sh
Labels: building

#231 Travis updates
  .travis.yml
  tests/t001-ceed.c
Labels: 1-In Review, bug, testing

#237 Travis MFEM fix
  .travis.yml
Labels: 1-In Review, bug, building, testing

#238 Restore t308-f
  tests/t308-basis-f.f90
Labels: 1-In Review, bug, testing
