Repository CEED/libCEED, pull requests merged in 2020-04, with the labels that each got.

#499 Small doc fixes
  .readthedocs.yml
  doc/img/SphereSketch.svg
  doc/sphinx/source/FEMtheory.rst.inc
  doc/sphinx/source/conf.py
  doc/sphinx/source/libCEEDapi.rst
  examples/bps.rst
  examples/ceed/index.rst
  examples/fluids/index.rst
  examples/notation.rst
  examples/petsc/index.rst
  examples/solids/README.rst
  examples/solids/index.rst
Labels: 1-In Review, documentation

#505 Solids fixes
  examples/solids/Makefile
  examples/solids/elasticity.c
  examples/solids/qfunctions/hyperFS.h
  examples/solids/src/cloptions.c
  examples/solids/src/misc.c
  examples/solids/src/setupdm.c
Labels: 1-In Review, bug, examples

#508 Travis - only run lcov for linux + gcc + amd64
  .travis.yml
Labels: 1-In Review, CI

#512 Small fixes and cleanups
  README.rst
  doc/img/CubedSphere.svg
  examples/ceed/ex1-volume.h
  examples/ceed/ex2-surface.h
  examples/ceed/index.rst
  examples/fluids/advection.h
  examples/fluids/advection2d.h
  examples/fluids/common.h
  examples/fluids/densitycurrent.h
  examples/mfem/bp1.h
  examples/mfem/bp3.h
  examples/nek/bps/bps.h
  examples/petsc/index.rst
  examples/petsc/qfunctions/area/areacube.h
  examples/petsc/qfunctions/area/areasphere.h
  examples/petsc/qfunctions/bps/bp1.h
  examples/petsc/qfunctions/bps/bp1sphere.h
  examples/petsc/qfunctions/bps/bp2.h
  examples/petsc/qfunctions/bps/bp2sphere.h
  examples/petsc/qfunctions/bps/bp3.h
  examples/petsc/qfunctions/bps/bp3sphere.h
  examples/petsc/qfunctions/bps/bp4.h
  examples/petsc/qfunctions/bps/bp4sphere.h
  examples/petsc/qfunctions/bps/common.h
  examples/petsc/setup.h
  examples/petsc/setupsphere.h
  examples/solids/qfunctions/common.h
  examples/solids/qfunctions/constantForce.h
  examples/solids/qfunctions/hyperFS.h
  examples/solids/qfunctions/hyperSS.h
  examples/solids/qfunctions/linElas.h
  examples/solids/qfunctions/manufacturedForce.h
  examples/solids/qfunctions/manufacturedTrue.h
  examples/tutorials/img/QFunctionSketch.svg
  examples/tutorials/tutorial-0-ceed.ipynb
  examples/tutorials/tutorial-6-shell.ipynb
  gallery/ceed-gallerytemplate.h
  gallery/identity/ceed-identity.h
  gallery/mass1d/ceed-mass1dbuild.h
  gallery/mass1d/ceed-massapply.h
  gallery/mass2d/ceed-mass2dbuild.h
  gallery/mass3d/ceed-mass3dbuild.h
  gallery/poisson1d/ceed-poisson1dapply.h
  gallery/poisson1d/ceed-poisson1dbuild.h
  gallery/poisson2d/ceed-poisson2dapply.h
  gallery/poisson3d/ceed-poisson3dapply.h
  gallery/poisson3d/ceed-poisson3dbuild.h
  python/build_ceed_cffi.py
  python/ceed_qfunction.py
Labels: 1-In Review, enhancement

#511 Add support for level of refinements for viz
  examples/fluids/README.md
  examples/fluids/navierstokes.c
Labels: 1-In Review, PETSc, examples

#514 Travis - freeze OCCA at 327badb until new OCCA backend mergend
  .travis.yml
Labels: 1-In Review, CI, OCCA

#504 Solids - Add Twist BCs and Strain Energy
  doc/sphinx/source/conf.py
  examples/solids/README.rst
  examples/solids/elasticity.c
  examples/solids/elasticity.h
  examples/solids/index.rst
  examples/solids/qfunctions/constantForce.h
  examples/solids/qfunctions/hyperFS.h
  examples/solids/qfunctions/hyperSS.h
  examples/solids/qfunctions/linElas.h
  examples/solids/qfunctions/manufacturedForce.h
  examples/solids/src/boundary.c
  examples/solids/src/cloptions.c
  examples/solids/src/matops.c
  examples/solids/src/setupdm.c
  examples/solids/src/setuplibceed.c
Labels: 1-In Review, examples

#515 Basis - move some functions to public API
  backends/occa/ceed-occa-basis.c
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-operator.c
  include/ceed-backend.h
  include/ceed.h
  interface/ceed-basis.c
Labels: 1-In Review, frontend, minor

#517 Update names in MAGMA restrictions
  backends/magma/ceed-magma-restriction.c
  backends/magma/ceed-magma.h
  backends/magma/magma_drestrictApply.cu
Labels: backend, minor

#518 More comments in CUDA backends
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda-reg/ceed-cuda-reg.c
  backends/cuda-reg/cuda-reg-basis.cu
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda-shared/ceed-cuda-shared.c
  backends/cuda/ceed-cuda-basis.c
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-qfunction-load.cpp
  backends/cuda/ceed-cuda-qfunction.c
  backends/cuda/ceed-cuda-restriction.c
  backends/cuda/ceed-cuda-vector.c
  backends/cuda/ceed-cuda.c
  backends/cuda/cuda-vector.cu
  examples/nek/bps/bps.h
  examples/petsc/qfunctions/bps/common.h
Labels: 1-In Review, CUDA, minor

#519 Ref - drop unneeded malloc and memcpy for strided restrictions
  backends/ref/ceed-ref-restriction.c
Labels: 1-In Review, CPU, minor

#520 CeedElemRestrictionGetOffsets
  backends/blocked/ceed-blocked-operator.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda/ceed-cuda-restriction.c
  backends/magma/ceed-magma-restriction.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-restriction.c
  include/ceed-backend.h
  include/ceed-impl.h
  interface/ceed-elemrestriction.c
  interface/ceed.c
  tests/junit.py
  tests/t214-elemrestriction.c
  tests/t215-elemrestriction.c
  tests/tap.sh
Labels: 1-In Review, enhancement, minor

#521 MAGMA: simplify build
  Makefile
  backends/magma/gccm.py
Labels: MAGMA, minor
