Repository CEED/libCEED, pull requests merged in 2020-10, with the labels that each got.

#641 CI - add hipMAGMA to CI
  .gitlab-ci.yml
  backends/magma/ceed-magma-basis.c
  tests/junit.py
  tests/python/test-0-ceed.py
Labels: 1-In Review

#643 Ceed - require 2+ chars to match in resource
  interface/ceed.c
Labels: 1-In Review, minor

#644 Travis - fix check against job name
  .travis.yml
Labels: 1-In Review, CI, minor

#633 enable HIP mode for MAGMA backend
  .gitlab-ci.yml
  Makefile
  README.rst
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma-det.c
  backends/magma/ceed-magma.c
  backends/magma/kernels/common/elem_restriction.h
  backends/magma/kernels/common/grad.h
  backends/magma/kernels/common/grad_device.h
  backends/magma/kernels/common/interp.h
  backends/magma/kernels/common/interp_device.h
  backends/magma/kernels/common/magma_common_device.h
  backends/magma/kernels/common/weight.h
  backends/magma/kernels/common/weight_device.h
  backends/magma/kernels/cuda/atomics.cuh
  backends/magma/kernels/cuda/grad_1d.cu
  backends/magma/kernels/cuda/grad_generic.cu
  backends/magma/kernels/cuda/gradn_2d.cu
  backends/magma/kernels/cuda/gradn_3d.cu
  backends/magma/kernels/cuda/gradt_2d.cu
  backends/magma/kernels/cuda/gradt_3d.cu
  backends/magma/kernels/cuda/interp_1d.cu
  backends/magma/kernels/cuda/interp_2d.cu
  backends/magma/kernels/cuda/interp_3d.cu
  backends/magma/kernels/cuda/interp_generic.cu
  backends/magma/kernels/cuda/magma_devptr.cu
  backends/magma/kernels/cuda/magma_drestrictApply.cu
  backends/magma/kernels/cuda/weight_1d.cu
  backends/magma/kernels/cuda/weight_2d.cu
  backends/magma/kernels/cuda/weight_3d.cu
  backends/magma/kernels/cuda/weight_generic.cu
  backends/magma/kernels/hip/atomics.hip.h
  backends/magma/kernels/hip/grad_1d.hip.cpp
  backends/magma/kernels/hip/grad_generic.hip.cpp
  backends/magma/kernels/hip/gradn_2d.hip.cpp
  backends/magma/kernels/hip/gradn_3d.hip.cpp
  backends/magma/kernels/hip/gradt_2d.hip.cpp
  backends/magma/kernels/hip/gradt_3d.hip.cpp
  backends/magma/kernels/hip/interp_1d.hip.cpp
  backends/magma/kernels/hip/interp_2d.hip.cpp
  backends/magma/kernels/hip/interp_3d.hip.cpp
  backends/magma/kernels/hip/interp_generic.hip.cpp
  backends/magma/kernels/hip/magma_devptr.hip.cpp
  backends/magma/kernels/hip/magma_drestrictApply.hip.cpp
  backends/magma/kernels/hip/weight_1d.hip.cpp
  backends/magma/kernels/hip/weight_2d.hip.cpp
  backends/magma/kernels/hip/weight_3d.hip.cpp
  backends/magma/kernels/hip/weight_generic.hip.cpp
  backends/magma/magma_dgemm_nontensor.c
  doc/sphinx/source/releasenotes.rst
  tests/junit.py
  tests/python/test-0-ceed.py
Labels: 1-In Review, CUDA, GPU, HIP, MAGMA

#647 change HIP blocksize
  backends/hip/ceed-hip-restriction.c
  backends/hip/ceed-hip.c
Labels: GPU, HIP
