Repository CEED/libCEED, pull requests merged in 2020-07, with the labels that each got.

#577 Vec - add CeedVectorTakeArray
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-vector.c
  backends/occa/ceed-occa-vector.c
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref-vector.c
  examples/nek/bps/bps.usr
  examples/petsc/area.c
  examples/petsc/bps.c
  examples/petsc/bpsraw.c
  examples/petsc/multigrid.c
  examples/petsc/setup.h
  examples/petsc/setupsphere.h
  examples/solids/elasticity.c
  examples/solids/src/matops.c
  examples/solids/src/misc.c
  examples/solids/src/setuplibceed.c
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed-vector.c
  interface/ceed.c
  tests/t104-vector.c
  tests/t109-vector-f.f90
  tests/t109-vector.c
Labels: 1-In Review, design, enhancement, minor

#578 Doc - add release note for CeedVectorTakeArray
  doc/sphinx/source/releasenotes.rst
Labels: 1-In Review, documentation, minor

#580 Rename master branch to main
  CONTRIBUTING.md
  README.rst
  azure-pipelines.yml
  doc/sphinx/source/libCEEDapi.rst
  doc/sphinx/source/releasenotes.rst
Labels: community

#584 Python - add operator diagonal assembly to the python interface
  python/ceed_operator.py
  tests/python/test-5-operator.py
  tests/t520-operator.c
  tests/t521-operator.c
  tests/t524-operator.c
Labels: 1-In Review, minor, python

#583 CUDA Vector Norm on Device
  Makefile
  backends/cuda/ceed-cuda-vector.c
  backends/cuda/ceed-cuda.c
  backends/cuda/ceed-cuda.h
Labels: 1-In Review, CUDA, GPU, enhancement

#586 CUDA - Fix Backend Setting LinearAssemble*
  backends/blocked/ceed-blocked-operator.c
  backends/cuda/ceed-cuda-operator.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-operator.c
Labels: 1-In Review, CUDA, bug, minor

#588 Solids - small fixes for CUDA compilation
  doc/sphinx/source/libCEEDapi.rst
  examples/solids/qfunctions/hyperFS.h
  examples/solids/qfunctions/hyperSS.h
  interface/ceed-qfunction.c
Labels: 1-In Review, bug, examples, minor

#589 Solids - add summary output for number of KSP its and throughput
  examples/solids/elasticity.c
Labels: 1-In Review, examples, minor

#585 Fortran - guard double calls to ceed*destroy in Fortran interface
  interface/ceed-fortran.c
  tests/t000-ceed-f.f90
  tests/t000-ceed.c
Labels: 1-In Review, bug, fortran, minor

#587 Ceed - add message storing error handler
  include/ceed-impl.h
  include/ceed.h
  interface/ceed.c
  python/build_ceed_cffi.py
  python/ceed.py
  python/ceed_basis.py
  python/ceed_elemrestriction.py
  python/ceed_operator.py
  python/ceed_qfunction.py
  python/ceed_vector.py
  tests/python/test-0-ceed.py
  tests/t005-ceed.c
Labels: 1-In Review, enhancement, python

#592 Small Python Testing Fixes
  .codecov.yml
  .travis.yml
  tests/python/test-0-ceed.py
Labels: 1-In Review, CI, minor, testing

#593 Travis - skip OCCA on non-AMD64 hardware to avoid random failures
  .travis.yml
Labels: 1-In Review, CI

#235 Test gitlab-ci
  .gitlab-ci.yml
  tests/junit.py
Labels: 1-In Review, CI, GPU

#594 backends/hip: exclude testing of unimplemented code
  Makefile
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda-reg/kernels/cuda-reg-basis.cu
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-qfunction.c
  backends/cuda/ceed-cuda-restriction.c
  backends/cuda/ceed-cuda.h
  backends/cuda/kernels/cuda-vector.cu
  backends/hip/ceed-hip-operator.c
  backends/hip/ceed-hip-qfunction.c
  backends/hip/ceed-hip-restriction.c
  backends/hip/ceed-hip.h
  backends/hip/kernels/hip-vector.hip.cpp
  backends/magma/kernels/atomics.cuh
  backends/magma/kernels/grad_1d.cu
  backends/magma/kernels/grad_device.cuh
  backends/magma/kernels/grad_generic.cu
  backends/magma/kernels/gradn_2d.cu
  backends/magma/kernels/gradn_3d.cu
  backends/magma/kernels/gradt_2d.cu
  backends/magma/kernels/gradt_3d.cu
  backends/magma/kernels/interp_1d.cu
  backends/magma/kernels/interp_2d.cu
  backends/magma/kernels/interp_3d.cu
  backends/magma/kernels/interp_device.cuh
  backends/magma/kernels/interp_generic.cu
  backends/magma/kernels/magma_common_device.cuh
  backends/magma/kernels/magma_devptr.cu
  backends/magma/kernels/magma_drestrictApply.cu
  backends/magma/kernels/weight_1d.cu
  backends/magma/kernels/weight_2d.cu
  backends/magma/kernels/weight_3d.cu
  backends/magma/kernels/weight_device.cuh
  backends/magma/kernels/weight_generic.cu
Labels: 1-In Review, CI, minor, testing

#595 Add SciPy20 Proceeding publication in CITING section and correspondin…
  README.rst
  doc/bib/references.bib
Labels: 1-In Review, documentation

#579 Op - add interface for multigrid level creation
  .travis.yml
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda/ceed-cuda-vector.c
  backends/cuda/kernels/cuda-vector.cu
  backends/hip/ceed-hip-vector.c
  backends/hip/kernels/hip-vector.hip.cpp
  backends/xsmm/ceed-xsmm-tensor.c
  examples/solids/README.rst
  examples/solids/elasticity.c
  examples/solids/elasticity.h
  examples/solids/src/cloptions.c
  examples/solids/src/matops.c
  examples/solids/src/misc.c
  examples/solids/src/setuplibceed.c
  gallery/scale/ceed-scale.c
  gallery/scale/ceed-scale.h
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-basis.c
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-vector.c
  interface/ceed.c
  python/ceed_basis.py
  python/ceed_operator.py
  python/ceed_vector.py
  tests/README.md
  tests/python/test-1-vector.py
  tests/python/test-5-operator.py
  tests/t119-vector-f.f90
  tests/t119-vector.c
  tests/t322-basis.c
  tests/t550-operator-f.f90
  tests/t550-operator.c
  tests/t551-operator.c
  tests/t552-operator-f.f90
  tests/t552-operator.c
  tests/t553-operator-f.f90
  tests/t553-operator.c
  tests/tap.sh
Labels: 1-In Review, design, frontend

#597 Fix CodeCov Reports
  .gitlab-ci.yml
  .travis.yml
  Makefile
  backends/cuda/ceed-cuda-vector.c
  backends/hip/ceed-hip-vector.c
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-qfunction.c
  interface/ceed-tensor.c
  interface/ceed-vector.c
  interface/ceed.c
  tests/t400-qfunction-f.f90
  tests/t400-qfunction-f.h
  tests/t401-qfunction-f.f90
  tests/t401-qfunction-f.h
  tests/t402-qfunction-f.f90
  tests/t500-operator-f.f90
  tests/t500-operator-f.h
  tests/t501-operator-f.f90
  tests/t501-operator-f.h
  tests/t502-operator-f.f90
  tests/t502-operator-f.h
  tests/t503-operator-f.f90
  tests/t504-operator-f.f90
  tests/t505-operator-f.f90
  tests/t506-operator-f.f90
  tests/t510-operator-f.f90
  tests/t510-operator-f.h
  tests/t511-operator-f.f90
  tests/t520-operator-f.f90
  tests/t521-operator-f.f90
  tests/t522-operator-f.f90
  tests/t522-operator-f.h
  tests/t523-operator-f.f90
  tests/t524-operator-f.f90
  tests/t530-operator-f.f90
  tests/t530-operator-f.h
  tests/t531-operator-f.f90
  tests/t531-operator-f.h
  tests/t532-operator-f.f90
  tests/t532-operator-f.h
  tests/t533-operator-f.f90
  tests/t534-operator-f.f90
  tests/t534-operator-f.h
  tests/t535-operator-f.f90
  tests/t535-operator-f.h
  tests/t536-operator-f.f90
  tests/t540-operator-f.f90
  tests/t540-operator-f.h
  tests/t550-operator-f.f90
  tests/t552-operator-f.f90
Labels: 1-In Review, CI, testing

#598 Small Cuda/Hip Fixes
  Makefile
  backends/cuda/ceed-cuda-qfunction-load.cpp
  backends/hip/ceed-hip-compile.cpp
  backends/hip/ceed-hip-qfunction-load.cpp
Labels: 1-In Review, GPU, minor
