Repository CEED/libCEED, pull requests merged in 2020-09, with the labels that each got.

#619 update HIP library links
  Makefile
Labels: HIP, minor

#622 Travis - pin OCCA at v1.1.0
  .travis.yml
Labels: 1-In Review, CI, OCCA

#625 Travis - allow icc failure for now
  .travis.yml
Labels: 1-In Review, CI, bug

#620 Enable under-integration for cuda-shared and cuda-gen backends
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda-shared/ceed-cuda-shared-basis.c
Labels: 1-In Review

#626 Small doc fixes
  doc/sphinx/source/libCEEDapi.rst
  doc/sphinx/source/releasenotes.rst
Labels: documentation

#627 Remove codedocs.xyz (operation looks unmaintained)
  .codedocs
  README.rst
  doc/sphinx/source/libCEEDapi.rst
  examples/tutorials/tutorial-0-ceed.ipynb
  examples/tutorials/tutorial-1-vector.ipynb
  examples/tutorials/tutorial-2-elemrestriction.ipynb
  examples/tutorials/tutorial-3-basis.ipynb
  examples/tutorials/tutorial-4-qfunction.ipynb
  examples/tutorials/tutorial-5-operator.ipynb
  examples/tutorials/tutorial-6-shell.ipynb
Labels: documentation

#610 QF - add interface to set device user function
  Makefile
  backends/cuda/ceed-cuda-qfunction-load.cpp
  backends/cuda/ceed-cuda-qfunction.c
  doc/sphinx/source/releasenotes.rst
  include/ceed-cuda.h
  include/ceed-hip.h
  include/ceed-impl.h
  interface/ceed-cuda.c
  interface/ceed-hip.c
  interface/ceed.c
Labels: 1-In Review, CUDA, GPU, design, enhancement

#629 Make - Intel oneAPI C/C++ compiler renamed to icx/icpx
  .travis.yml
  Makefile
Labels: 1-In Review, CI, bug, minor

#628 Make - install hashing headers, used in MFEM
  Makefile
  include/ceed-hash.h
  include/ceed-khash.h
Labels: 1-In Review, bug, building

#634 OCCA - update backend resource names to match other GPU backends
  Makefile
  README.rst
  backends/magma/ceed-magma-det.c
  backends/magma/ceed-magma.c
  backends/occa/ceed-occa.cpp
  examples/ceed/ex1-volume.c
  examples/ceed/ex2-surface.c
  examples/fluids/navierstokes.c
  examples/mfem/bp1.cpp
  examples/mfem/bp3.cpp
  examples/petsc/area.c
  examples/petsc/bps.c
  examples/petsc/bpsraw.c
  examples/petsc/bpssphere.c
  examples/petsc/multigrid.c
  examples/solids/elasticity.c
Labels: 1-In Review

#637 Jeremy/py debugging
  backends/opt/ceed-opt-operator.c
  interface/ceed-vector.c
  interface/ceed.c
  python/ceed.py
  python/ceed_basis.py
  python/ceed_elemrestriction.py
  python/ceed_operator.py
  python/ceed_qfunction.py
  python/ceed_qfunctioncontext.py
  python/ceed_vector.py
  tests/junit.py
  tests/python/test-0-ceed.py
Labels: 1-In Review, bug

#638 Make - add cpp files to code coverage
  Makefile
Labels: 1-In Review, CI, minor

#639 Make - update make info with better backend name display
  Makefile
Labels: 1-In Review, minor

#640 Tests - delete stray okl file
  tests/t537-operator.okl
Labels: 1-In Review, minor
