Repository CEED/libCEED, pull requests merged in 2020-02, with the labels that each got.

#453 Operator - only assemble diag for nonzero QF entries
  backends/ref/ceed-ref-operator.c
  include/ceed-impl.h
  include/ceed.h
  include/ceedf.h
  interface/ceed-fortran.c
  interface/ceed-vector.c
  interface/ceed.c
  python/ceed_constants.py
  python/ceed_vector.py
  tests/python/test-1-vector.py
  tests/t108-vector-f.f90
  tests/t108-vector.c
  tests/t534-operator-f.f90
  tests/t534-operator.c
Labels: 1-In Review, CPU, enhancement, performance

#450 [Tests] Removed testing padded entries
  tests/output/t208-elemrestriction.out
  tests/t208-elemrestriction.c
Labels: testing

#424 Enable MAGMA non-tensor basis
  Makefile
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma-restriction.c
  backends/magma/ceed-magma-restriction_cuda.cu
  backends/magma/ceed-magma.c
  backends/magma/ceed-magma.h
  backends/magma/magma_dbasisApply_grad.cu
  backends/magma/magma_dbasisApply_interp.cu
  backends/magma/magma_dbasisApply_weight.cu
  backends/magma/magma_drestrictApply.cu
  tests/tap.sh
Labels: 1-In Review, MAGMA, backend

#457 CITING.md
  CITING.md
  doc/bib/references.bib
Labels: 1-In Review, documentation

#464 Diagonal Computation Fix
  backends/ref/ceed-ref-operator.c
  examples/petsc/bpsraw.c
  examples/petsc/qfunctions/bps/bp2.h
  examples/petsc/qfunctions/bps/bp2.okl
  examples/petsc/qfunctions/bps/bp4.h
  examples/petsc/qfunctions/bps/bp4.okl
Labels: 1-In Review, CPU, bug, examples
