Repository CEED/libCEED, pull requests merged in 2020-11, with the labels that each got.

#656 MAGMA - re-enable MAGMA CI on GitLab
  .gitlab-ci.yml
  Makefile
Labels: 1-In Review, CI, MAGMA

#657 Remove doc/doxygenlayout.xml
  doc/doxygenlayout.xml
Labels: documentation

#659 Add the C++11 flag to the XL C++ flags
  Makefile
Labels: 1-In Review, building

#658 CI - Use GitHub Actions
  .github/workflows/c-fortran-test-hardware.yml
  .github/workflows/c-fortran-test-icc.sh
  .github/workflows/c-fortran-test-icc.yml
  .github/workflows/c-fortran-test-linux-osx.yml
  .github/workflows/c-fortran-test-style.yml
  .github/workflows/julia-documentation.yml
  .github/workflows/julia-test-with-style.yml
  .github/workflows/python-test-with-style.yml
  .gitlab-ci.yml
  .travis.yml
  README.rst
  examples/nek/nek-examples.sh
  julia/LibCEED.jl/docs/make.jl
  tests/junit.py
  tests/tap.sh
Labels: 1-In Review, CI

#655 Solids - new BCs
  examples/solids/README.rst
  examples/solids/elasticity.c
  examples/solids/elasticity.h
  examples/solids/qfunctions/common.h
  examples/solids/src/boundary.c
  examples/solids/src/cloptions.c
  examples/solids/src/matops.c
  examples/solids/src/setuplibceed.c
Labels: 1-In Review, examples

#661 Some suggestions for the Rust interface
  rust/src/basis.rs
  rust/src/elem_restriction.rs
  rust/src/lib.rs
  rust/src/operator.rs
  rust/src/qfunction.rs
  rust/src/vector.rs
Labels: 1-In Review, Rust, design, frontend

#662 Python - drop class variables
  python/ceed.py
  python/ceed_basis.py
  python/ceed_elemrestriction.py
  python/ceed_operator.py
  python/ceed_qfunction.py
  python/ceed_qfunctioncontext.py
  python/ceed_vector.py
Labels: 1-In Review, Python, minor

#602 Rust interface
  .github/workflows/rust-documentation.yml
  .github/workflows/rust-test-with-style.yml
  doc/sphinx/source/api/CeedOperator.rst
  doc/sphinx/source/api/CeedQFunction.rst
  doc/sphinx/source/api/CeedVector.rst
  doc/sphinx/source/ffi.rst
  rust/.gitignore
  rust/Cargo.toml
  rust/build.rs
  rust/src/basis.rs
  rust/src/elem_restriction.rs
  rust/src/lib.rs
  rust/src/operator.rs
  rust/src/qfunction.rs
  rust/src/vector.rs
Labels: 1-In Review, Rust

#663 README - update ffi information
  README.rst
  doc/sphinx/source/releasenotes.rst
Labels: 1-In Review, minor
