Repository CEED/libCEED, pull requests merged in 2020-06, with the labels that each got.

#554 Convert CUDA ref/reg/shared E-Layout
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda/ceed-cuda-basis.c
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-restriction.c
  backends/cuda/ceed-cuda.h
  backends/magma/ceed-magma-operator.c
  backends/magma/ceed-magma-restriction.c
  backends/magma/ceed-magma.c
  backends/occa/ceed-occa-restrict.c
  backends/ref/ceed-ref-restriction.c
  include/ceed-backend.h
  include/ceed-impl.h
  interface/ceed-elemrestriction.c
  interface/ceed-fortran.c
  tests/t201-elemrestriction-f.f90
  tests/t201-elemrestriction.c
  tests/t204-elemrestriction.c
  tests/t205-elemrestriction.c
  tests/t206-elemrestriction.c
  tests/t207-elemrestriction.c
  tests/tap.sh
Labels: 1-In Review, CUDA, MAGMA, testing

#555 README - update Travis badge
  README.rst
Labels: 1-In Review, minor

#553 CUDA/MAGMA - add AssembleLinearQFunction
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda/ceed-cuda-operator.c
  backends/ref/ceed-ref-operator.c
Labels: 1-In Review, CUDA, enhancement

#552 Composite Operator support for AssembleLinearDiag/PBDiag
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref.c
  backends/ref/ceed-ref.h
  examples/ceed/ex1-volume.c
  examples/ceed/ex2-surface.c
  include/ceed-backend.h
  interface/ceed-operator.c
  tests/t538-operator.c
  tests/tap.sh
Labels: 1-In Review, CPU, enhancement

#556 Improve Developer Documentation
  doc/sphinx/source/libCEEDapi.rst
  doc/sphinx/source/libCEEDdev.rst
  interface/ceed-elemrestriction.c
Labels: 1-In Review, documentation

#557 Doc - fix L-vector indexing in dev docs
  doc/sphinx/source/libCEEDdev.rst
  interface/ceed-elemrestriction.c
Labels: 1-In Review, minor

#558 Rename Functions
  backends/blocked/ceed-blocked-operator.c
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-restriction.c
  backends/magma/ceed-magma-restriction.c
  backends/occa/ceed-occa-operator.c
  backends/occa/ceed-occa-restrict.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref-restriction.c
  backends/xsmm/ceed-xsmm-tensor.c
  doc/sphinx/source/releasenotes.rst
  examples/petsc/setup.h
  examples/solids/src/matops.c
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed.c
  tests/t530-operator-f.f90
  tests/t530-operator.c
  tests/t531-operator-f.f90
  tests/t531-operator.c
  tests/t532-operator-f.f90
  tests/t532-operator.c
  tests/t533-operator-f.f90
  tests/t533-operator.c
  tests/t534-operator-f.f90
  tests/t534-operator.c
  tests/t535-operator-f.f90
  tests/t535-operator.c
  tests/t536-operator-f.f90
  tests/t536-operator.c
  tests/t537-operator.c
  tests/t538-operator.c
Labels: 1-In Review, minor

#562 python: use precise ext suffix instead of globs in tests
  tests/python/test-4-qfunction.py
  tests/python/test-5-operator.py
Labels: python, testing

#559 PETSc - fix PETSc test parameters for CUDA backends
  examples/petsc/bps.c
  examples/petsc/bpsraw.c
Labels: 1-In Review, bug, minor

#560 LinearAssemble Improvements
  backends/ref/ceed-ref-operator.c
  doc/sphinx/source/releasenotes.rst
  examples/petsc/setup.h
  examples/solids/src/matops.c
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed.c
  tests/t533-operator-f.f90
  tests/t533-operator.c
  tests/t534-operator-f.f90
  tests/t534-operator.c
  tests/t535-operator-f.f90
  tests/t535-operator.c
  tests/t536-operator-f.f90
  tests/t536-operator.c
  tests/t537-operator.c
  tests/t538-operator.c
Labels: 1-In Review, design, enhancement, minor

#563 XSMM - use v1.16
  .travis.yml
  backends/xsmm/ceed-xsmm-tensor.c
  backends/xsmm/ceed-xsmm.h
Labels: 1-In Review, CPU, minor

#567 Travis - fix shallow clone of XSMM 1.16
  .travis.yml
  backends/xsmm/ceed-xsmm.h
Labels: 1-In Review, CI, minor

#568 Small CUDA Tidying
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda-reg/ceed-cuda-reg-basis.c
  backends/cuda-reg/ceed-cuda-reg-restriction.c
  backends/cuda-reg/ceed-cuda-reg.c
  backends/cuda-reg/cuda-reg-basis.cu
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda-shared/ceed-cuda-shared.c
  backends/cuda/ceed-cuda-basis.c
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-qfunction-load.cpp
  backends/cuda/ceed-cuda-qfunction.c
  backends/cuda/ceed-cuda-restriction.c
  backends/cuda/ceed-cuda-vector.c
  backends/cuda/ceed-cuda.c
  backends/cuda/ceed-cuda.h
  backends/cuda/cuda-vector.cu
  examples/petsc/bpsraw.c
  tests/t318-basis.c
  tests/tap.sh
Labels: 1-In Review, CUDA, minor

#569 CUDA - shared basis needs minimum of 1 elem per block
  backends/cuda-shared/ceed-cuda-shared-basis.c
Labels: 1-In Review, CUDA, minor

#564 CUDA - LinearAssemble*Diagonal
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda.c
  backends/cuda/ceed-cuda.h
  backends/ref/ceed-ref-operator.c
  examples/petsc/setup.h
Labels: 1-In Review, CUDA, enhancement

#561 Ceed - add IsDeterministic
  README.rst
  backends/avx/ceed-avx-blocked.c
  backends/avx/ceed-avx-serial.c
  backends/blocked/ceed-blocked.c
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda-reg/ceed-cuda-reg.c
  backends/cuda-shared/ceed-cuda-shared.c
  backends/cuda/ceed-cuda.c
  backends/magma/ceed-magma.c
  backends/memcheck/ceed-memcheck-blocked.c
  backends/memcheck/ceed-memcheck-serial.c
  backends/opt/ceed-opt-blocked.c
  backends/opt/ceed-opt-operator.c
  backends/opt/ceed-opt-serial.c
  backends/ref/ceed-ref.c
  backends/template/ceed-tmpl-sub.c
  backends/template/ceed-tmpl.c
  backends/xsmm/ceed-xsmm-blocked.c
  backends/xsmm/ceed-xsmm-serial.c
  gallery/poisson1d/ceed-poisson1dapply.c
  gallery/poisson1d/ceed-poisson1dapply.h
  gallery/poisson1d/ceed-poisson1dbuild.c
  gallery/poisson1d/ceed-poisson1dbuild.h
  gallery/poisson2d/ceed-poisson2dapply.c
  gallery/poisson2d/ceed-poisson2dapply.h
  gallery/poisson2d/ceed-poisson2dbuild.c
  gallery/poisson2d/ceed-poisson2dbuild.h
  gallery/poisson3d/ceed-poisson3dapply.c
  gallery/poisson3d/ceed-poisson3dapply.h
  gallery/poisson3d/ceed-poisson3dbuild.c
  gallery/poisson3d/ceed-poisson3dbuild.h
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed-fortran.c
  interface/ceed-vector.c
  interface/ceed.c
  tests/t004-ceed-f.f90
  tests/t004-ceed.c
Labels: 1-In Review, documentation, enhancement

#571 Deterministic MAGMA Backend
  Makefile
  README.rst
  backends/magma/ceed-magma-det.c
  backends/magma/ceed-magma.c
  tests/tap.sh
Labels: 1-In Review, MAGMA, minor

#570 Add Debug Mode
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/magma/ceed-magma.h
  backends/occa/ceed-occa-basis.c
  backends/occa/ceed-occa-okl.c
  backends/occa/ceed-occa-operator.c
  backends/occa/ceed-occa-qfunction-noop.c
  backends/occa/ceed-occa-qfunction-op.c
  backends/occa/ceed-occa-qfunction.c
  backends/occa/ceed-occa-restrict.c
  backends/occa/ceed-occa-vector.c
  backends/occa/ceed-occa.c
  backends/occa/ceed-occa.h
  include/ceed-backend.h
  include/ceed-impl.h
  include/ceed.h
  interface/ceed.c
Labels: 1-In Review, enhancement, minor

#573 CODE_OF_CONDUCT: upgrade to Contributor Covenant 2.0
  CODE_OF_CONDUCT.md
Labels: documentation

#574 Use Released for CI
  .travis.yml
Labels: 1-In Review, CI, testing

#566 Solids - enable use of GPU vectors
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda-reg/ceed-cuda-reg.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda-shared/ceed-cuda-shared.c
  backends/cuda/ceed-cuda-operator.c
  backends/cuda/ceed-cuda-qfunction-load.cpp
  backends/cuda/ceed-cuda-qfunction.c
  backends/cuda/ceed-cuda.c
  backends/magma/ceed-magma-det.c
  backends/magma/ceed-magma.c
  examples/petsc/bpsraw.c
  examples/petsc/multigrid.c
  examples/petsc/setup.h
  examples/solids/elasticity.c
  examples/solids/elasticity.h
  examples/solids/src/cloptions.c
  examples/solids/src/matops.c
  examples/solids/src/misc.c
  examples/solids/src/setuplibceed.c
  gallery/identity/ceed-identity.h
  interface/ceed-qfunction.c
  interface/ceed-vector.c
  tests/t412-qfunction.c
Labels: 1-In Review, CUDA, examples

#572 Name the kernels in cuda-gen.
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
Labels: 1-In Review, backend, minor
