Repository CEED/libCEED, pull requests merged in 2020-12, with the labels that each got.

#664 Actions - update for change in ICC CI example repo
  .github/workflows/c-fortran-test-icc.yml
Labels: 1-In Review, CI

#666 actions - use Ubuntu 20.04 for icc
  .github/workflows/c-fortran-test-icc.yml
Labels: 1-In Review

#665 Update citing info with user manual
  .mailmap
  README.rst
  doc/bib/references.bib
  doc/sphinx/source/releasenotes.rst
Labels: documentation

#671 CI: move GitHub Actions to ubuntu 20.04
  .github/workflows/c-fortran-test-hardware.yml
  .github/workflows/c-fortran-test-linux-osx.yml
  .github/workflows/c-fortran-test-style.yml
  .github/workflows/julia-documentation.yml
  .github/workflows/julia-test-with-style.yml
  .github/workflows/python-test-with-style.yml
  .github/workflows/rust-documentation.yml
  .github/workflows/rust-test-with-style.yml
  doc/sphinx/requirements.txt
  doc/sphinx/source/conf.py
Labels: CI

#668 Add hip-shared and hip-gen backends
  Makefile
  README.rst
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.h
  backends/hip-gen/ceed-hip-gen-operator.c
  backends/hip-gen/ceed-hip-gen-qfunction.c
  backends/hip-gen/ceed-hip-gen.c
  backends/hip-gen/ceed-hip-gen.h
  backends/hip-shared/ceed-hip-shared-basis.c
  backends/hip-shared/ceed-hip-shared.c
  backends/hip-shared/ceed-hip-shared.h
  backends/hip-shared/kernels/hip-shared-basis.hip.cpp
  backends/hip/ceed-hip.c
  backends/hip/ceed-hip.h
  doc/sphinx/source/releasenotes.rst
  include/ceed-backend.h
Labels: GPU, HIP, backend

#675 README: petscspace_degree -> degree (PETSc examples)
  README.rst
Labels: documentation, minor

#677 doc: fixed some typos
  doc/sphinx/source/libCEEDapi.rst
Labels: documentation, minor

#676 Remove unused CUDA atomicAdd code from hip-gen
  README.rst
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
Labels: GPU, HIP, minor

#680 doc: update to sphinxcontrib-bibtex 2.1
  doc/sphinx/requirements.txt
  doc/sphinx/source/references.rst
Labels: documentation

#681 doc fixes
  README.rst
  doc/sphinx/requirements.txt
  doc/sphinx/source/conf.py
  doc/sphinx/source/references.bib
  examples/index.rst
  examples/solids/index.rst
Labels: documentation

#684 Rust - use enum values from bindgen
  rust/src/lib.rs
Labels: 1-In Review, Rust, bug
