Repository CEED/libCEED, pull requests merged in 2021-04, with the labels that each got.

#723 update release notes
  doc/sphinx/source/releasenotes.rst
Labels: documentation, minor

#730 interface - improved resource matching check
  include/ceed/ceed.h
  interface/ceed.c
  tests/junit.py
  tests/t006-ceed.c
  tests/t007-ceed.c
  tests/t008-ceed.c
  tests/tap.sh
Labels: 1-In Review, enhancement, interface

#732 header - update minor version in header definition
  include/ceed/ceed.h
Labels: 1-In Review, bug, minor

#733 Extra error message for uncompiled backends
  backends/ceed-backend-list.h
  backends/ceed-backend-weak.c
  include/ceed/backend.h
  interface/ceed-register.c
  interface/ceed.c
  tests/junit.py
  tests/tap.sh
Labels: 1-In Review, bug, minor

#739 Copy Ceed Object References
  .github/workflows/rust-test-with-style.yml
  backends/ref/ceed-ref-basis.c
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-tensor.c
  interface/ceed-vector.c
  interface/ceed.c
  tests/t009-ceed.c
  tests/t120-vector.c
  tests/t216-elemrestriction.c
  tests/t307-basis.c
  tests/t403-qfunction.c
  tests/t508-operator.c
Labels: 1-In Review, enhancement, interface

#743 tidy - small fixes
  .gitlab-ci.yml
  backends/ceed-backend-weak.c
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  interface/ceed-basis.c
  interface/ceed-operator.c
  interface/ceed.c
Labels: 1-In Review, minor

#740 Update device ID selection for HIP/CUDA/MAGMA backends
  README.rst
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda-shared/ceed-cuda-shared.c
  backends/cuda-shared/ceed-cuda-shared.h
  backends/cuda/ceed-cuda.c
  backends/hip-gen/ceed-hip-gen.c
  backends/hip-gen/ceed-hip-gen.h
  backends/hip-shared/ceed-hip-shared-basis.c
  backends/hip-shared/ceed-hip-shared.c
  backends/hip-shared/ceed-hip-shared.h
  backends/hip/ceed-hip.c
  backends/magma/ceed-magma-det.c
  backends/magma/ceed-magma-restriction.c
  backends/magma/ceed-magma.c
Labels: CUDA, GPU, HIP, MAGMA

#745 gitlab - rearange the script for clearer output
  .gitlab-ci.yml
  Makefile
  common.mk
  examples/fluids/navierstokes.c
  examples/petsc/include/petscmacros.h
  examples/petsc/src/petscutils.c
  examples/solids/elasticity.h
  examples/solids/src/setupdm.c
Labels: 1-In Review, CI

#746 make - small updates to makefile for python test move
  Makefile
Labels: 1-In Review, bug, building, minor

#744 PointwiseMult and AXPY convenience functions
  include/ceed-impl.h
  include/ceed/ceed.h
  interface/ceed-vector.c
  interface/ceed.c
  tests/t121-vector.c
  tests/t122-vector.c
Labels: 1-In Review, minor

#748 Improve documentation linking
  doc/sphinx/source/conf.py
  doc/sphinx/source/releasenotes.rst
Labels: documentation

#751 Allow number of quad points per element to be set for Op
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-operator.c
Labels: 1-In Review, minor

#752 python - add pointwisemult and axpy
  backends/cuda/ceed-cuda-vector.c
  backends/cuda/kernels/cuda-vector.cu
  backends/hip/ceed-hip-vector.c
  backends/hip/kernels/hip-vector.hip.cpp
  interface/ceed-vector.c
  python/ceed_vector.py
  python/tests/test-1-vector.py
  tests/t122-vector.c
Labels: 1-In Review, Python, minor

#757 vec - add CeedVectorScale
  .github/workflows/julia-test-with-style.yml
  .github/workflows/rust-test-with-style.yml
  backends/cuda/ceed-cuda-qfunctioncontext.c
  backends/cuda/ceed-cuda-vector.c
  backends/cuda/kernels/cuda-vector.cu
  backends/hip/ceed-hip-qfunctioncontext.c
  backends/hip/ceed-hip-vector.c
  backends/hip/kernels/hip-vector.hip.cpp
  backends/occa/ceed-occa-qfunctioncontext.cpp
  backends/occa/ceed-occa-qfunctioncontext.hpp
  backends/ref/ceed-ref-qfunctioncontext.c
  include/ceed-impl.h
  include/ceed/ceed.h
  interface/ceed-elemrestriction.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-vector.c
  interface/ceed.c
  julia/LibCEED.jl/docs/src/Ceed.md
  julia/LibCEED.jl/docs/src/CeedVector.md
  julia/LibCEED.jl/src/Ceed.jl
  julia/LibCEED.jl/src/CeedVector.jl
  julia/LibCEED.jl/src/LibCEED.jl
  julia/LibCEED.jl/src/generated/libceed_api.jl
  julia/LibCEED.jl/src/generated/libceed_common.jl
  julia/LibCEED.jl/test/rundevtests.jl
  julia/LibCEED.jl/test/runtests.jl
  python/ceed_vector.py
  python/tests/test-1-vector.py
  rust/src/vector.rs
  tests/junit.py
  tests/t123-vector.c
  tests/t404-qfunction.c
  tests/tap.sh
Labels: 1-In Review, minor

#750 qf - allow identity qfunctions to have in and out EVAL_NONE
  backends/blocked/ceed-blocked-operator.c
  backends/blocked/ceed-blocked.h
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/opt/ceed-opt-operator.c
  backends/opt/ceed-opt.h
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref.h
  interface/ceed-qfunction.c
  tests/t509-operator.c
Labels: 1-In Review, minor

#753 CI - unset PETSC_DIR
  .gitlab-ci.yml
Labels: 1-In Review, CI, bug, minor

#758 Small Code Coverage Updates
  .github/workflows/rust-test-with-style.yml
  backends/occa/ceed-occa-qfunctioncontext.cpp
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  tests/junit.py
  tests/t404-qfunction.c
  tests/tap.sh
Labels: 1-In Review, CI, minor

#762 Docs: Tiny rewording in Intro
  doc/sphinx/source/intro.rst
Labels: documentation
