Repository CEED/libCEED, pull requests merged in 2021-06, with the labels that each got.

#774 Check Release Notes
  .github/workflows/release-notes.yml
  doc/sphinx/source/releasenotes.rst
Labels: 1-In Review, CI, enhancement

#775 actions - turn off release notes check on main
  .github/workflows/release-notes.yml
Labels: 1-In Review, CI, bug

#776 Jeremy/actions fix again
  .github/workflows/release-notes.yml
Labels: 1-In Review, CI, bug

#777 Update citations to libCEED 0.8 users manual on Zenodo
  README.rst
  doc/bib/references.bib
Labels: documentation

#780 git - add *.a to petsc gitignore
  examples/petsc/.gitignore
Labels: 1-In Review, minor

#725 Document release procedures
  RELEASING.md
Labels: 1-In Review, documentation

#782 clang - silence some pedantic warnings, fixes #742
  backends/ceed-backend-weak.c
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/hip-gen/ceed-hip-gen-qfunction.c
  backends/magma/ceed-magma-basis.c
  doc/sphinx/source/releasenotes.rst
  include/ceed/ceed.h
  interface/ceed-elemrestriction.c
  interface/ceed-fortran.c
  interface/ceed.c
Labels: 1-In Review, building, minor

#749 fdm - minor fixes
  backends/ref/ceed-ref-operator.c
  doc/sphinx/source/releasenotes.rst
  include/ceed/backend.h
  interface/ceed-basis.c
  python/ceed_basis.py
  python/tests/output/test_305.out
  python/tests/test-3-basis.py
  python/tests/test-5-operator.py
  tests/output/t304-basis-f.out
  tests/output/t304-basis.out
  tests/output/t305-basis-f.out
  tests/output/t305-basis.out
  tests/t304-basis-f.f90
  tests/t304-basis.c
  tests/t305-basis-f.f90
  tests/t305-basis.c
  tests/t540-operator.c
  tests/t541-operator.c
  tests/t541-operator.h
Labels: 1-In Review, bug
