Repository CEED/libCEED, pull requests merged in 2021-08, with the labels that each got.

#796 doc - add citing yaml
  CITATION.cff
  README.rst
  RELEASING.md
Labels: 1-In Review, documentation, minor

#795 Refactor Preconditioning Ingredients
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda/ceed-cuda-operator.c
  backends/hip-gen/ceed-hip-gen-operator.c
  backends/hip/ceed-hip-operator.c
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref.c
  backends/ref/ceed-ref.h
  doc/sphinx/source/releasenotes.rst
  include/ceed/backend.h
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  interface/ceed-vector.c
Labels: 1-In Review, design

#797 Refactor tests to reduce use of output
  interface/ceed-basis.c
  interface/ceed-fortran.c
  python/build_ceed_cffi.py
  python/ceed_elemrestriction.py
  python/tests/output/test_202.out
  python/tests/output/test_208.out
  python/tests/output/test_301.out
  python/tests/output/test_304.out
  python/tests/test-2-elemrestriction.py
  python/tests/test-3-basis.py
  tests/output/t202-elemrestriction-f.out
  tests/output/t202-elemrestriction.out
  tests/output/t203-elemrestriction.out
  tests/output/t208-elemrestriction-f.out
  tests/output/t208-elemrestriction.out
  tests/output/t213-elemrestriction.out
  tests/output/t301-basis-f.out
  tests/output/t301-basis.out
  tests/output/t302-basis-f.out
  tests/output/t302-basis.out
  tests/t201-elemrestriction-f.f90
  tests/t201-elemrestriction.c
  tests/t202-elemrestriction-f.f90
  tests/t202-elemrestriction.c
  tests/t203-elemrestriction.c
  tests/t208-elemrestriction-f.f90
  tests/t208-elemrestriction.c
  tests/t213-elemrestriction.c
  tests/t301-basis-f.f90
  tests/t301-basis.c
  tests/t302-basis-f.f90
  tests/t302-basis.c
Labels: 1-In Review, minor, testing

#798 Add missing codecov exclusions
  interface/ceed-vector.c
  tests/t304-basis-f.f90
  tests/t305-basis-f.f90
Labels: 1-In Review, minor

#799 Solids - some cleanup
  examples/solids/qfunctions/FSCurrent-NH1.h
  examples/solids/qfunctions/FSCurrent-NH2.h
  examples/solids/qfunctions/FSInitial-MR1.h
  examples/solids/qfunctions/FSInitial-NH1.h
  examples/solids/qfunctions/FSInitial-NH2.h
Labels: 1-In Review

#703 doc: replace recommonmark with MyST
  Doxyfile
  README.md
  README.rst
  doc/sphinx/requirements.txt
  doc/sphinx/source/FEMtheory.rst.inc
  doc/sphinx/source/api/Ceed.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/css/altair-plot.css
  doc/sphinx/source/ffi.md
  doc/sphinx/source/ffi.rst
  doc/sphinx/source/gettingstarted.md
  doc/sphinx/source/gettingstarted.rst
  doc/sphinx/source/index.md
  doc/sphinx/source/index.rst
  doc/sphinx/source/intro.md
  doc/sphinx/source/libCEEDapi.md
  doc/sphinx/source/libCEEDapi.rst
  doc/sphinx/source/libCEEDdev.md
  doc/sphinx/source/libCEEDdev.rst
  doc/sphinx/source/references.bib
  doc/sphinx/source/references.rst
  doc/sphinx/source/releasenotes.md
  doc/sphinx/source/releasenotes.rst
  examples/README.md
  examples/README.rst
  examples/bps.md
  examples/bps.rst
  examples/ceed/index.md
  examples/ceed/index.rst
  examples/fluids/index.md
  examples/fluids/index.rst
  examples/index.md
  examples/index.rst
  examples/notation.md
  examples/notation.rst
  examples/petsc/index.md
  examples/petsc/index.rst
  examples/solids/README.md
  examples/solids/README.rst
  examples/solids/index.md
  examples/solids/index.rst
  rust/libceed/tests/version-numbers.rs
Labels: documentation

#800 Fluids - Small refactor
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/advection.c
  examples/fluids/problems/advection2d.c
  examples/fluids/problems/densitycurrent.c
  examples/fluids/problems/eulervortex.c
  examples/fluids/src/setuplibceed.c
Labels: examples, 1-In Review

#801 Refactoring Solids to Remove Switches
  Makefile
  examples/solids/Makefile
  examples/solids/elasticity.c
  examples/solids/elasticity.h
  examples/solids/include/boundary.h
  examples/solids/include/cl-options.h
  examples/solids/include/matops.h
  examples/solids/include/misc.h
  examples/solids/include/petsc-macros.h
  examples/solids/include/setup-dm.h
  examples/solids/include/setup-libceed.h
  examples/solids/include/structs.h
  examples/solids/include/utils.h
  examples/solids/index.md
  examples/solids/problems/cl-problems.h
  examples/solids/problems/finite-strain-mooney-rivlin-initial-1.c
  examples/solids/problems/finite-strain-neo-hookean-current-1.c
  examples/solids/problems/finite-strain-neo-hookean-current-2.c
  examples/solids/problems/finite-strain-neo-hookean-initial-1.c
  examples/solids/problems/finite-strain-neo-hookean-initial-2.c
  examples/solids/problems/linear.c
  examples/solids/problems/mooney-rivlin.c
  examples/solids/problems/mooney-rivlin.h
  examples/solids/problems/neo-hookean.c
  examples/solids/problems/neo-hookean.h
  examples/solids/problems/problems.c
  examples/solids/problems/problems.h
  examples/solids/problems/small-strain-neo-hookean.c
  examples/solids/qfunctions/common.h
  examples/solids/qfunctions/constant-force.h
  examples/solids/qfunctions/finite-strain-mooney-rivlin-initial-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-current-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-current-2.h
  examples/solids/qfunctions/finite-strain-neo-hookean-initial-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-initial-2.h
  examples/solids/qfunctions/linear.h
  examples/solids/qfunctions/manufactured-force.h
  examples/solids/qfunctions/manufactured-true.h
  examples/solids/qfunctions/small-strain-neo-hookean.h
  examples/solids/qfunctions/traction-boundary.h
  examples/solids/src/boundary.c
  examples/solids/src/cl-options.c
  examples/solids/src/matops.c
  examples/solids/src/misc.c
  examples/solids/src/setup-dm.c
  examples/solids/src/setup-libceed.c
  examples/solids/tests-output/MR-strain.csv
  examples/solids/tests-output/MR-strain1.csv
  examples/solids/tests-output/NH-strain.csv
  include/ceed/backend.h
Labels: enhancement, examples, 1-In Review
