Repository CEED/libCEED, pull requests merged in 2021-10, with the labels that each got.

#821 actions - update to codecov action v2
  .github/workflows/rust-test-with-style.yml
Labels: 1-In Review, CI

#818 Examples - doc
  examples/fluids/README.md
  examples/fluids/conv_test.sh
  examples/fluids/index.md
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/eulervortex.c
  examples/fluids/tests-output/fluids-navierstokes-conv-euler.csv
  examples/fluids/tests-output/fluids-navierstokes-euler-explicit.bin
  examples/fluids/tests-output/fluids-navierstokes-euler-implicit-test-t1.bin
  examples/fluids/tests-output/fluids-navierstokes-euler-implicit-test-t2.bin
  examples/fluids/tests-output/fluids-navierstokes-euler-implicit-test-t3.bin
  examples/fluids/tests-output/fluids-navierstokes-euler-implicit-test-t4.bin
  examples/fluids/tests-output/fluids-navierstokes-euler-implicit.bin
  examples/index.md
  examples/solids/README.md
  examples/solids/qfunctions/finite-strain-mooney-rivlin-initial-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-current-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-current-2.h
  examples/solids/qfunctions/finite-strain-neo-hookean-initial-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-initial-2.h
Labels: documentation, examples, 1-In Review

#812 Promote Operator check to public API; Strengthen composite Operator check
  doc/sphinx/source/releasenotes.md
  examples/python/tutorial-5-operator.ipynb
  examples/rust/ex1-volume/src/main.rs
  examples/rust/ex2-surface/src/main.rs
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-operator.c
  python/ceed_operator.py
  python/tests/test-5-operator.py
  rust/libceed/src/lib.rs
  rust/libceed/src/operator.rs
Labels: enhancement, minor, 1-In Review

#820 Add OCCA backend warning
  .gitlab-ci.yml
  Makefile
  backends/occa/ceed-occa.cpp
  doc/sphinx/source/releasenotes.md
  include/ceed-backend.h
  include/ceed-hash.h
  include/ceed-khash.h
Labels: minor, 1-In Review

#833 makefile - respond to either V or VERBOSE
  Makefile
Labels: minor, 1-In Review
