Repository CEED/libCEED, pull requests merged in 2021-11, with the labels that each got.

#831 doc - minor typo
  Makefile
  doc/sphinx/source/libCEEDdev.md
  doc/sphinx/source/releasenotes.md
Labels: minor, 1-In Review

#845 readme - fix binder url
  README.md
Labels: bug, minor, 1-In Review

#841 QFunction multi source support
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/cuda/ceed-cuda-qfunction.c
  backends/cuda/ceed-cuda.c
  backends/hip-gen/ceed-hip-gen-qfunction.c
  backends/hip/ceed-hip-qfunction.c
  doc/sphinx/source/releasenotes.md
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/advection2d.h
  examples/fluids/qfunctions/densitycurrent.h
  examples/fluids/qfunctions/eulervortex.h
  examples/fluids/qfunctions/mass.h
  examples/fluids/qfunctions/setupgeo.h
  examples/fluids/qfunctions/setupgeo2d.h
  examples/nek/bps/bps.h
  examples/petsc/qfunctions/area/areacube.h
  examples/petsc/qfunctions/area/areasphere.h
  examples/petsc/qfunctions/bps/bp1.h
  examples/petsc/qfunctions/bps/bp1sphere.h
  examples/petsc/qfunctions/bps/bp2.h
  examples/petsc/qfunctions/bps/bp2sphere.h
  examples/petsc/qfunctions/bps/bp3.h
  examples/petsc/qfunctions/bps/bp3sphere.h
  examples/petsc/qfunctions/bps/bp4.h
  examples/petsc/qfunctions/bps/bp4sphere.h
  examples/solids/qfunctions/constant-force.h
  examples/solids/qfunctions/finite-strain-mooney-rivlin-initial-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-current-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-current-2.h
  examples/solids/qfunctions/finite-strain-neo-hookean-initial-1.h
  examples/solids/qfunctions/finite-strain-neo-hookean-initial-2.h
  examples/solids/qfunctions/linear.h
  examples/solids/qfunctions/manufactured-force.h
  examples/solids/qfunctions/manufactured-true.h
  examples/solids/qfunctions/small-strain-neo-hookean.h
  include/ceed-impl.h
  include/ceed/backend.h
  include/ceed/jit-tools.h
  interface/ceed-jit-tools.c
  interface/ceed-qfunction.c
  python/tests/output/test_402.out
  tests/output/t402-qfunction-f.out
  tests/output/t402-qfunction.out
  tests/t406-qfunction-helper.h
  tests/t406-qfunction.c
  tests/t406-qfunction.h
Labels: enhancement, design, GPU, 1-In Review

#847 xsmm - fix minor inconsistency in filename
  backends/xsmm/ceed-xsmm-tensor-f32.c
  backends/xsmm/ceed-xsmm-tensor-f64.c
Labels: bug, minor, 1-In Review

#846 doc - fix minor spacing bug in release notes
  doc/sphinx/source/releasenotes.md
Labels: bug, minor, documentation, 1-In Review

#838 Fix iwyu target
  Makefile
  doc/sphinx/source/libCEEDdev.md
Labels: bug, minor, 1-In Review

#840 Macro for Debug without Ceed Context
  backends/ceed-backend-list.h
  backends/ceed-backend-weak.c
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda/ceed-cuda-qfunction-load.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/hip/ceed-hip-qfunction-load.cpp
  backends/magma/ceed-magma-basis.c
  backends/occa/ceed-occa-cpu-operator.cpp
  doc/sphinx/source/releasenotes.md
  gallery/ceed-gallery-list.h
  gallery/ceed-gallery-weak.c
  include/ceed-impl.h
  include/ceed/backend.h
  interface/ceed-cuda.c
  interface/ceed-hip.c
  interface/ceed-operator.c
  interface/ceed-qfunction-register.c
  interface/ceed-qfunction.c
  interface/ceed.c
Labels: minor, 1-In Review

#848 Solids: fixed duplicate definitions in structs.h
  examples/solids/include/structs.h
Labels: duplicate, 1-In Review

#849 petsc - use PetscFECreateLagrange
  examples/petsc/include/petscutils.h
  examples/petsc/src/petscutils.c
  examples/solids/include/setup-dm.h
  examples/solids/src/setup-dm.c
Labels: minor, PETSc
