Repository CEED/libCEED, pull requests merged in 2022-02, with the labels that each got.

#878 H(div) basis constructor
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref.c
  backends/ref/ceed-ref.h
  include/ceed-impl.h
  include/ceed/ceed.h
  interface/ceed-basis.c
  interface/ceed-types.c
  interface/ceed.c
  julia/LibCEED.jl/src/Globals.jl
  julia/LibCEED.jl/src/generated/libceed_bindings.jl
  julia/LibCEED.jl/test/output/Float32/b1.out
  julia/LibCEED.jl/test/output/Float32/b2.out
  julia/LibCEED.jl/test/output/Float32/b3.out
  julia/LibCEED.jl/test/output/Float64/b1.out
  julia/LibCEED.jl/test/output/Float64/b2.out
  julia/LibCEED.jl/test/output/Float64/b3.out
  python/ceed_constants.py
  python/tests/output/test_300.out
  rust/libceed/src/lib.rs
  tests/output/t300-basis-f.out
  tests/output/t300-basis.out
  tests/output/t320-basis-f.out
  tests/output/t320-basis.out
  tests/output/t330-basis.out
  tests/t320-basis.c
  tests/t321-basis.c
  tests/t322-basis.c
  tests/t323-basis.c
  tests/t324-basis.c
  tests/t325-basis.c
  tests/t330-basis.c
  tests/t330-basis.h
  tests/t331-basis.c
  tests/t332-basis.c
  tests/t510-operator.c
  tests/t511-operator.c
  tests/t520-operator.c
  tests/t521-operator.c
  tests/t522-operator.c
  tests/t523-operator.c
  tests/t524-operator.c
  tests/t536-operator.c
  tests/t551-operator.c
  tests/t563-operator.c
Labels: interface, backend, testing, 1-In Review

#807 PETSc examples: assemble matrix analytically instead of coloring
  examples/petsc/multigrid.c
  examples/solids/elasticity.c
  examples/solids/include/structs.h
  examples/solids/src/misc.c
Labels: examples, GPU, PETSc

#885 PETSc - set minimum version for examples
  examples/fluids/README.md
  examples/fluids/navierstokes.h
  examples/fluids/problems/advection.c
  examples/fluids/problems/advection2d.c
  examples/fluids/problems/densitycurrent.c
  examples/fluids/problems/eulervortex.c
  examples/petsc/README.md
  examples/petsc/area.c
  examples/petsc/bps.c
  examples/petsc/bpssphere.c
  examples/petsc/include/petscmacros.h
  examples/petsc/include/petscutils.h
  examples/petsc/include/petscversion.h
  examples/petsc/multigrid.c
  examples/petsc/src/petscutils.c
  examples/solids/README.md
  examples/solids/elasticity.h
  examples/solids/include/petsc-macros.h
  examples/solids/src/setup-dm.c
Labels: minor, PETSc, 1-In Review

#888 doc - update release notes
  doc/sphinx/source/releasenotes.md
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-types.c
Labels: documentation, 1-In Review

#886 ex - better namespacing of petsc ex headers
  examples/fluids/navierstokes.h
  examples/petsc/area.h
  examples/petsc/bps.h
  examples/petsc/bpssphere.h
  examples/petsc/include/areaproblemdata.h
  examples/petsc/include/bcfunctions.h
  examples/petsc/include/bpsproblemdata.h
  examples/petsc/include/libceedsetup.h
  examples/petsc/include/matops.h
  examples/petsc/include/petscutils.h
  examples/petsc/include/petscversion.h
  examples/petsc/include/sphereproblemdata.h
  examples/petsc/include/structs.h
  examples/solids/elasticity.h
  examples/solids/include/boundary.h
  examples/solids/include/cl-options.h
  examples/solids/include/matops.h
  examples/solids/include/misc.h
  examples/solids/include/setup-dm.h
  examples/solids/include/setup-libceed.h
  examples/solids/include/structs.h
  examples/solids/include/utils.h
Labels: minor, 1-In Review

#881 Fluids - update mesh creating and remove problem-specific BCs
  examples/fluids/README.md
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/advection.c
  examples/fluids/problems/advection2d.c
  examples/fluids/problems/densitycurrent.c
  examples/fluids/problems/eulervortex.c
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/advection2d.h
  examples/fluids/qfunctions/eulervortex.h
  examples/fluids/src/cloptions.c
  examples/fluids/src/setupdm.c
  examples/fluids/src/setuplibceed.c
  examples/petsc/src/petscutils.c
  examples/solids/src/setup-dm.c
Labels: examples, PETSc

#890 prove - add t330 float exclusion
  tests/tap.sh
Labels: bug, minor, 1-In Review, CI

#887 QFContext - create labels for registered fields
  doc/sphinx/source/.gitignore
  gallery/identity/ceed-identity.c
  include/ceed-impl.h
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-qfunctioncontext.c
  tests/t330-basis.c
  tests/t330-basis.h
  tests/t407-qfunction.c
  tests/t525-operator.c
Labels: enhancement, minor, 1-In Review

#891 CI Update
  .gitlab-ci.yml
  azure-pipelines.yml
Labels: 1-In Review, CI

#889 Element Restriction Oriented
  backends/ref/ceed-ref-restriction.c
  backends/ref/ceed-ref.c
  backends/ref/ceed-ref.h
  include/ceed-impl.h
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-elemrestriction.c
  interface/ceed.c
  tests/t200-elemrestriction.c
  tests/t201-elemrestriction.c
  tests/t202-elemrestriction.c
  tests/t203-elemrestriction.c
  tests/t204-elemrestriction.c
  tests/t205-elemrestriction.c
  tests/t208-elemrestriction.c
  tests/t213-elemrestriction.c
  tests/t220-elemrestriction.c
Labels: backend, 1-In Review

#892 op - fix small leak in composite ctx label
  interface/ceed-operator.c
  tests/t525-operator.c
Labels: bug, minor, 1-In Review

#897 Vector: error-free path for get/take array when size=0
  interface/ceed-vector.c
  tests/t109-vector.c
Labels: minor

#895 qf - remove stray character
  interface/ceed-qfunction.c
Labels: bug, minor, 1-In Review

#902 backends cuda-shared: fix launch bounds to avoid invalid z dimension
  .gitlab-ci.yml
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/magma/ceed-magma-restriction.c
  backends/magma/ceed-magma.h
Labels: bug, CUDA

#901 Fix context memory leak
  interface/ceed-qfunction.c
Labels: bug, 1-In Review

#905 petsc - use SETERRQ over SETERRQ1
  examples/fluids/navierstokes.c
  examples/fluids/src/cloptions.c
  examples/petsc/multigrid.c
  examples/solids/elasticity.c
Labels: minor, PETSc, 1-In Review

#907 Fix basis qref size mismatch
  interface/ceed-preconditioning.c
Labels: bug, minor, 1-In Review

#893 HIP: add atomics flag and more kernel launch bounds for performance improvements
  Makefile
  README.md
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.h
  backends/hip-gen/ceed-hip-gen-operator.c
  backends/hip-ref/ceed-hip-ref-qfunction-load.cpp
  backends/hip/ceed-hip-compile.cpp
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma.c
  backends/magma/ceed-magma.h
  backends/magma/kernels/common/elem_restriction.h
  backends/magma/kernels/common/grad.h
  backends/magma/kernels/common/interp.h
  backends/magma/kernels/common/magma_common_device.h
  backends/magma/kernels/common/weight.h
  backends/magma/kernels/cuda/grad_1d.cu
  backends/magma/kernels/cuda/gradn_2d.cu
  backends/magma/kernels/cuda/gradn_3d.cu
  backends/magma/kernels/cuda/gradt_2d.cu
  backends/magma/kernels/cuda/gradt_3d.cu
  backends/magma/kernels/cuda/interp_1d.cu
  backends/magma/kernels/cuda/interp_2d.cu
  backends/magma/kernels/cuda/interp_3d.cu
  backends/magma/kernels/cuda/magma_drestrictApply.cu
  backends/magma/kernels/cuda/weight_1d.cu
  backends/magma/kernels/cuda/weight_2d.cu
  backends/magma/kernels/cuda/weight_3d.cu
  backends/magma/kernels/hip/grad_1d.hip.cpp
  backends/magma/kernels/hip/gradn_2d.hip.cpp
  backends/magma/kernels/hip/gradn_3d.hip.cpp
  backends/magma/kernels/hip/gradt_2d.hip.cpp
  backends/magma/kernels/hip/gradt_3d.hip.cpp
  backends/magma/kernels/hip/interp_1d.hip.cpp
  backends/magma/kernels/hip/interp_2d.hip.cpp
  backends/magma/kernels/hip/interp_3d.hip.cpp
  backends/magma/kernels/hip/magma_drestrictApply.hip.cpp
  backends/magma/kernels/hip/weight_1d.hip.cpp
  backends/magma/kernels/hip/weight_2d.hip.cpp
  backends/magma/kernels/hip/weight_3d.hip.cpp
  backends/magma/magma_grad.c
  backends/magma/magma_interp.c
  backends/magma/magma_weight.c
Labels: enhancement, GPU, HIP

#906 make - fix env BACKENDS detection
  Makefile
Labels: bug, minor, building, 1-In Review

#909 ci: update lv after system upgrade
  .gitlab-ci.yml
Labels: CI
