Repository CEED/libCEED, pull requests merged in 2022-11, with the labels that each got.

#1083 ci - update codecov action version
  .github/workflows/rust-test-with-style.yml
Labels: 1-In Review, CI

#1085 minor - clearer GPU QF/Op kernel names
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-ref/ceed-cuda-ref-qfunction-load.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/hip-ref/ceed-hip-ref-qfunction-load.cpp
Labels: minor, GPU, 1-In Review

#1091 Update CEED_EVAL_DIV/INTERP
  backends/blocked/ceed-blocked-operator.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-operator.c
Labels: backend, 1-In Review

#1097 minor - missing $ in code samples
  README.md
Labels: minor, 1-In Review
