Repository CEED/libCEED, pull requests merged in 2022-09, with the labels that each got.

#1058 LIBXSMM CI Update
  .gitlab-ci.yml
Labels: 1-In Review, CI

#1063 Fluids - Blasius: Some Minor Modifications
  examples/fluids/README.md
  examples/fluids/problems/blasius.c
  examples/fluids/qfunctions/blasius.h
  examples/fluids/tests-output/blasius_test.yaml
  examples/fluids/tests-output/fluids-navierstokes-blasius.bin
Labels: enhancement, examples, 1-In Review

#1065 Fix t568 bug
  tests/junit.py
  tests/t568-operator.c
  tests/t568-operator.h
Labels: bug, testing

#1021 Change the initialization logic for `useCollograd`.
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
Labels: 1-In Review

#1066 Lazy access of qf kernel name and path
  include/ceed-impl.h
  interface/ceed-qfunction.c
Labels: minor, 1-In Review

#1071 minor - fix type in basis struct
  include/ceed-impl.h
Labels: minor, 1-In Review

#1070 removed tap.sh and updated junit.py
  .github/workflows/c-fortran-test-hardware.yml
  Makefile
  examples/ceed/ex1-volume.c
  examples/ceed/ex2-surface.c
  examples/mfem/Makefile
  tests/junit-xml/.gitignore
  tests/junit-xml/.travis.yml
  tests/junit-xml/MANIFEST.in
  tests/junit-xml/README.rst
  tests/junit-xml/junit_xml/__init__.py
  tests/junit-xml/setup.py
  tests/junit-xml/test_junit_xml.py
  tests/junit-xml/tox.ini
  tests/junit.py
  tests/tap.sh
Labels: enhancement, 1-In Review

#1050 Refactor `cuda-gen` and `hip-gen` backends.
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda-ref/ceed-cuda-ref.h
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda-shared/ceed-cuda-shared.h
  backends/cuda-shared/kernels/cuda-shared-basis.cu
  backends/cuda/ceed-cuda-common.h
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.h
  backends/hip-gen/ceed-hip-gen-operator.c
  backends/hip-gen/ceed-hip-gen-qfunction.c
  backends/hip-gen/ceed-hip-gen.h
  backends/hip-ref/ceed-hip-ref.h
  backends/hip-shared/ceed-hip-shared-basis.c
  backends/hip-shared/ceed-hip-shared.h
  backends/hip/ceed-hip-common.h
  doc/sphinx/source/releasenotes.md
  include/ceed/jit-source/cuda/cuda-atomic-add-fallback.h
  include/ceed/jit-source/cuda/cuda-gen-templates.h
  include/ceed/jit-source/cuda/cuda-jit.h
  include/ceed/jit-source/cuda/cuda-shared-basis-read-write-templates.h
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-templates.h
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor.h
  include/ceed/jit-source/cuda/cuda-shared-basis.h
  include/ceed/jit-source/cuda/cuda-types.h
  include/ceed/jit-source/hip/hip-gen-templates.h
  include/ceed/jit-source/hip/hip-jit.h
  include/ceed/jit-source/hip/hip-shared-basis-read-write-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor.h
  include/ceed/jit-source/hip/hip-shared-basis.h
  include/ceed/jit-source/hip/hip-types.h
Labels: enhancement, GPU, CUDA, 1-In Review, HIP
