Repository CEED/libCEED, pull requests merged in 2022-05, with the labels that each got.

#851 Shock Tube + YZB Discontinuity Capturing
  doc/sphinx/source/references.bib
  examples/fluids/README.md
  examples/fluids/index.md
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/shocktube.c
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/advection2d.h
  examples/fluids/qfunctions/densitycurrent.h
  examples/fluids/qfunctions/shocktube.h
  examples/fluids/src/cloptions.c
  examples/fluids/tests-output/fluids-navierstokes-shocktube-explicit-su-yzb.bin
Labels: examples, PETSc, 1-In Review

#954 op - include num_elem and num_qpts in view
  doc/sphinx/source/releasenotes.md
  examples/rust/ex1-volume/src/main.rs
  examples/rust/ex2-surface/src/main.rs
  examples/rust/ex3-vector-volume/src/main.rs
  examples/rust/ex4-vector-surface/src/main.rs
  include/ceed-impl.h
  include/ceed/ceed.h
  interface/ceed-fortran.c
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  interface/ceed-qfunction.c
  julia/LibCEED.jl/test/rundevtests.jl
  julia/LibCEED.jl/test/runtests.jl
  python/ceed_operator.py
  python/tests/output/test_402.out
  python/tests/output/test_413.out
  python/tests/output/test_504.out
  python/tests/output/test_523.out
  python/tests/test-5-operator.py
  rust/libceed/src/operator.rs
  tests/output/t402-qfunction-f.out
  tests/output/t402-qfunction.out
  tests/output/t413-qfunction-f.out
  tests/output/t413-qfunction.out
  tests/output/t504-operator-f.out
  tests/output/t504-operator.out
  tests/output/t523-operator-f.out
  tests/output/t523-operator.out
  tests/t523-operator-f.f90
  tests/t523-operator.c
Labels: enhancement, minor, 1-In Review

#955 Small bug in operator cloning
  interface/ceed-preconditioning.c
Labels: bug

#958 examples/fluids cleaning
  examples/fluids/channel.yaml
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/advection.c
  examples/fluids/problems/advection2d.c
  examples/fluids/problems/blasius.c
  examples/fluids/problems/channel.c
  examples/fluids/problems/densitycurrent.c
  examples/fluids/problems/eulervortex.c
  examples/fluids/problems/newtonian.c
  examples/fluids/problems/shocktube.c
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/advection2d.h
  examples/fluids/qfunctions/blasius.h
  examples/fluids/qfunctions/channel.h
  examples/fluids/qfunctions/densitycurrent.h
  examples/fluids/qfunctions/eulervortex.h
  examples/fluids/qfunctions/newtonian.h
  examples/fluids/qfunctions/newtonian_types.h
  examples/fluids/qfunctions/shocktube.h
  examples/fluids/qfunctions/stabilization_types.h
  examples/fluids/src/misc.c
  examples/fluids/src/setupdm.c
  examples/fluids/src/setuplibceed.c
  examples/fluids/tests-output/fluids-navierstokes-channel.bin
Labels: examples

#961 Fix fluids for CUDA_ERROR_INVALID_PTX and enable lv-cuda
  .gitlab-ci.yml
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/advection2d.h
  examples/fluids/qfunctions/channel.h
  examples/fluids/qfunctions/newtonian_types.h
Labels: examples, CI

#957 CI Debugging
  .gitlab-ci.yml
Labels: bug, Nek5000, 1-In Review, CI

#969 ElemRestriction and Basis input checking
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
Labels: enhancement, minor, 1-In Review

#956 pc - use refcounting in fallback clone creation
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
Labels: enhancement, 1-In Review

#970 Audit object encapsulation
  include/ceed/backend.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  interface/ceed-qfunction.c
  interface/ceed-vector.c
  interface/ceed.c
Labels: enhancement, minor, 1-In Review

#971 Relax comp_stride check
  interface/ceed-elemrestriction.c
Labels: bug, minor, 1-In Review

#972 Fix qf fallback cloning
  include/ceed-impl.h
  interface/ceed-preconditioning.c
  interface/ceed-qfunction.c
Labels: bug
