Repository CEED/libCEED, pull requests merged in 2022-12, with the labels that each got.

#1106 ci: update to rocm-5.3.3
  .gitlab-ci.yml
Labels: GPU, CI

#1099 Check for single active basis/restr
  interface/ceed-operator.c
Labels: bug, minor, 1-In Review

#1100 Immutable multigrid operators
  interface/ceed-preconditioning.c
Labels: minor, 1-In Review

#1105 Add CeedCompositeOperatorGetMultiplicity
  doc/sphinx/source/releasenotes.md
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  tests/t554-operator.c
Labels: bug, 1-In Review

#1108 Makefile: avoid creating null.d file (fix #1107)
  Makefile
Labels: building

#1113 Julia QRef/QWeight Fix
  interface/ceed-basis.c
  julia/LibCEED.jl/src/Basis.jl
Labels: 1-In Review

#1115 fluids: device bind petsc and fix HLLC for CUDA
  examples/fluids/problems/newtonian.c
  examples/fluids/qfunctions/freestream_bc.h
  examples/fluids/qfunctions/newtonian_types.h
  examples/fluids/src/cloptions.c
Labels: examples

#1119 CI: update to rocm-5.4.1
  .gitlab-ci.yml
Labels: CI

#1120 Rust coverage
  .github/workflows/rust-test-with-style.yml
Labels: CI

#1121 Add Ratel junit.py updates
  tests/junit.py
Labels: enhancement, minor, 1-In Review, CI

#1096 Fluids-newtonian: Stabilization coefficients dependent on polynomial degree
  examples/fluids/README.md
  examples/fluids/blasius.yaml
  examples/fluids/channel.yaml
  examples/fluids/navierstokes.c
  examples/fluids/problems/newtonian.c
  examples/fluids/src/cloptions.c
  examples/fluids/tests-output/blasius_stgtest.yaml
  examples/fluids/tests-output/blasius_test.yaml
Labels: examples, 1-In Review

#1122 Fix leak in CeedCompositeOperatorGetMultiplicity
  interface/ceed-preconditioning.c
Labels: bug, minor, 1-In Review

#1124 Release 0.11
  .github/workflows/python-wheels.yml
  .gitignore
  AUTHORS
  CITATION.cff
  Doxyfile
  README.md
  RELEASING.md
  ceed.pc.template
  doc/img/libCEED-decomposition.svg
  doc/sphinx/source/conf.py
  doc/sphinx/source/libCEEDapi.md
  doc/sphinx/source/releasenotes.md
  examples/fluids/index.md
  examples/rust/ex1-volume/Cargo.toml
  examples/rust/ex2-surface/Cargo.toml
  examples/rust/ex3-vector-volume/Cargo.toml
  examples/rust/ex4-vector-surface/Cargo.toml
  examples/rust/mesh/Cargo.toml
  include/ceed/ceed.h
  pyproject.toml
  python/build_ceed_cffi.py
  python/ceed_elemrestriction.py
  python/make-wheels.sh
  python/test-wheel.sh
  rust/libceed-sys/Cargo.toml
  rust/libceed-sys/README.md
  rust/libceed-sys/build.rs
  rust/libceed/Cargo.toml
  rust/libceed/README.md
  setup.py
Labels: release preparation

#1082 Vortex shedding / flow past cylinder
  .gitignore
  doc/sphinx/source/references.bib
  examples/fluids/README.md
  examples/fluids/index.md
  examples/fluids/meshes/Makefile
  examples/fluids/meshes/cylinder.geo
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/freestream_bc.c
  examples/fluids/problems/newtonian.c
  examples/fluids/qfunctions/newtonian.h
  examples/fluids/qfunctions/newtonian_state.h
  examples/fluids/qfunctions/newtonian_types.h
  examples/fluids/src/cloptions.c
  examples/fluids/src/setuplibceed.c
  examples/fluids/vortexshedding.yaml
Labels: examples, 0-WIP
