Repository CEED/libCEED, pull requests merged in 2022-06, with the labels that each got.

#976 GPU assembly: fix possible basis loading offset error
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
Labels: bug, GPU, CUDA, HIP

#978 op - more data in view
  interface/ceed-operator.c
  julia/LibCEED.jl/test/rundevtests.jl
  python/tests/output/test_504.out
  python/tests/output/test_523.out
  tests/output/t504-operator-f.out
  tests/output/t504-operator.out
  tests/output/t523-operator-f.out
  tests/output/t523-operator.out
Labels: enhancement, minor, 1-In Review

#977 Add debugging output to fallback creation
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/cuda-ref/ceed-cuda-ref.c
  backends/cuda-ref/ceed-cuda-ref.h
  backends/hip-gen/ceed-hip-gen.h
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/hip-ref/ceed-hip-ref.c
  backends/hip-ref/ceed-hip-ref.h
  include/ceed-impl.h
  interface/ceed-preconditioning.c
  interface/ceed.c
Labels: enhancement, minor, 1-In Review

#981 pc - fix GPU single operator fallback
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
  include/ceed-impl.h
  interface/ceed-preconditioning.c
  interface/ceed.c
Labels: bug, GPU, 1-In Review

#982 fixed include memcpy segv error
  interface/ceed-jit-tools.c
  tests/t406-qfunction-scales.h
Labels: bug, 1-In Review

#985 Solids leak
  examples/solids/elasticity.c
  interface/ceed-preconditioning.c
Labels: 1-In Review

#986 Fluids - Fix memory leak
  examples/fluids/problems/advection.c
  examples/fluids/problems/advection2d.c
  examples/fluids/problems/blasius.c
  examples/fluids/problems/channel.c
  examples/fluids/problems/eulervortex.c
  examples/fluids/problems/newtonian.c
  examples/fluids/problems/shocktube.c
  examples/fluids/problems/stg_shur14.c
  examples/fluids/src/setuplibceed.c
Labels: examples, 1-In Review

#989 ref - handle num_elem=0 case for qf assembly
  backends/ref/ceed-ref-operator.c
Labels: bug, CPU, 1-In Review

#990 Fix assembly for operators with size zero
  backends/cuda-ref/ceed-cuda-ref-qfunctioncontext.c
  interface/ceed-elemrestriction.c
  interface/ceed-preconditioning.c
Labels: bug, 1-In Review

#996 GPU - copy ElemRestr index values passed on host
  backends/cuda-ref/ceed-cuda-restriction.c
  backends/hip-ref/ceed-hip-ref-restriction.c
  doc/sphinx/source/releasenotes.md
Labels: bug, GPU, 1-In Review

#993 Fluids BCs performance updates
  doc/sphinx/source/releasenotes.md
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/src/misc.c
  examples/fluids/src/setupts.c
Labels: examples, performance, 1-In Review

#998 CeedOperatorAssemblePointBlockDiagonal: fix restriction sizes for subdomain integral
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
  doc/sphinx/source/releasenotes.md
  interface/ceed-preconditioning.c
Labels: bug

#991 Memcheck QFContext
  backends/memcheck/ceed-memcheck-blocked.c
  backends/memcheck/ceed-memcheck-qfunction.c
  backends/memcheck/ceed-memcheck-qfunctioncontext.c
  backends/memcheck/ceed-memcheck-serial.c
  backends/memcheck/ceed-memcheck.h
  doc/sphinx/source/releasenotes.md
  examples/fluids/navierstokes.c
  examples/fluids/problems/advection.c
  examples/fluids/problems/advection2d.c
  examples/fluids/problems/densitycurrent.c
  examples/fluids/problems/newtonian.c
  examples/fluids/problems/shocktube.c
  include/ceed-impl.h
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-qfunctioncontext.c
  interface/ceed.c
  tests/t404-qfunction.c
  tests/t408-qfunction.c
Labels: enhancement, 1-In Review

#997 fluids - add preloading
  examples/fluids/src/setupts.c
Labels: enhancement, examples, 1-In Review

#988 Test for assembly w/non-square D
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
  doc/sphinx/source/releasenotes.md
  include/ceed-impl.h
  include/ceed/backend.h
  include/ceed/jit-source/cuda/cuda-ref-operator-assemble-diagonal.h
  include/ceed/jit-source/cuda/cuda-ref-operator-assemble.h
  include/ceed/jit-source/hip/hip-ref-operator-assemble-diagonal.h
  include/ceed/jit-source/hip/hip-ref-operator-assemble.h
  interface/ceed-basis.c
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  tests/t568-operator.c
Labels: bug, 1-In Review

#1001 gpu - fix setting device id
  backends/cuda-gen/ceed-cuda-gen.c
  backends/cuda-ref/ceed-cuda-ref.c
  backends/cuda-shared/ceed-cuda-shared.c
  backends/cuda/ceed-cuda-common.c
  backends/cuda/ceed-cuda-common.h
  backends/hip-gen/ceed-hip-gen.c
  backends/hip-ref/ceed-hip-ref.c
  backends/hip-shared/ceed-hip-shared.c
  backends/hip/ceed-hip-common.c
  backends/hip/ceed-hip-common.h
  doc/sphinx/source/releasenotes.md
Labels: bug, GPU, 1-In Review

#1005 basis - add CeedBasisCreateProlongation
  doc/sphinx/source/releasenotes.md
  include/ceed/ceed.h
  interface/ceed-basis.c
  interface/ceed-preconditioning.c
Labels: enhancement, minor, 1-In Review

#1006 Fix /gpu/*/gen backends for op with all CEED_BASIS_COLLOCATED
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
Labels: bug, GPU, CUDA, 1-In Review, HIP

#1012 basis - use ncomp from 'from' basis for projection
  include/ceed/ceed.h
  interface/ceed-basis.c
  interface/ceed-preconditioning.c
Labels: minor, 1-In Review

#1008 Small Doc Fixes
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  RELEASING.md
  doc/sphinx/source/api/CeedBasis.rst
  doc/sphinx/source/api/CeedElemRestriction.rst
  doc/sphinx/source/api/CeedOperator.rst
  doc/sphinx/source/api/CeedQFunction.rst
  doc/sphinx/source/api/CeedVector.rst
  doc/sphinx/source/ffi.md
  doc/sphinx/source/intro.md
  doc/sphinx/source/libCEEDapi.md
  doc/sphinx/source/libCEEDdev.md
  doc/sphinx/source/precision.md
  doc/sphinx/source/releasenotes.md
  examples/README.md
  examples/bps.md
  examples/ceed/README.md
  examples/fluids/README.md
  examples/nek/README.md
  examples/notation.md
  examples/solids/README.md
  julia/LibCEED.jl/README.md
  rust/libceed-sys/README.md
  tests/README.md
Labels: documentation, 1-In Review
