Repository CEED/libCEED, pull requests merged in 2022-01, with the labels that each got.

#867 rust - looser lifetime restrictions
  rust/libceed/src/basis.rs
  rust/libceed/src/elem_restriction.rs
  rust/libceed/src/lib.rs
  rust/libceed/src/operator.rs
  rust/libceed/src/qfunction.rs
  rust/libceed/src/vector.rs
Labels: 1-In Review, Rust

#869 Update GetMultiplicity function (E^T * E * 1) to work for H(div) space
  interface/ceed-elemrestriction.c
Labels: interface, 1-In Review

#865 Fluids - Fix bug in Stabilization (SU/SUPG)
  doc/sphinx/requirements.txt
  doc/sphinx/source/references.bib
  doc/sphinx/source/releasenotes.md
  examples/fluids/README.md
  examples/fluids/index.md
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/advection.c
  examples/fluids/problems/advection2d.c
  examples/fluids/problems/densitycurrent.c
  examples/fluids/problems/eulervortex.c
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/advection2d.h
  examples/fluids/qfunctions/densitycurrent.h
  examples/fluids/qfunctions/eulervortex.h
  examples/fluids/src/setuplibceed.c
  examples/fluids/src/setupts.c
Labels: bug, examples, 1-In Review

#871 op - add ctx setting interface for operators
  Doxyfile
  doc/sphinx/requirements.txt
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-operator.c
  interface/ceed-qfunctioncontext.c
  tests/t407-qfunction.c
  tests/t525-operator.c
Labels: enhancement, 1-In Review

#872 Rust - impl cloning Ceed
  rust/libceed/src/lib.rs
Labels: enhancement, minor, 1-In Review, Rust

#866 Use DMPlexGetLocalOffsets
  examples/fluids/navierstokes.h
  examples/fluids/src/setupdm.c
  examples/fluids/src/setuplibceed.c
  examples/petsc/area.c
  examples/petsc/bps.c
  examples/petsc/bpssphere.c
  examples/petsc/include/petscutils.h
  examples/petsc/multigrid.c
  examples/petsc/src/libceedsetup.c
  examples/petsc/src/petscutils.c
  examples/solids/include/setup-libceed.h
  examples/solids/src/setup-dm.c
  examples/solids/src/setup-libceed.c
Labels: examples, PETSc, 0-WIP

#873 actions - bump version of run-on-arch-action
  .github/workflows/c-fortran-test-hardware.yml
Labels: minor, 1-In Review, CI

#874 vec/ctx - make backend restore function optional
  backends/avx/ceed-avx-tensor-f32.c
  backends/avx/ceed-avx-tensor-f64.c
  backends/cuda-ref/ceed-cuda-ref-qfunctioncontext.c
  backends/cuda-ref/ceed-cuda-vector.c
  backends/hip-ref/ceed-hip-ref-qfunctioncontext.c
  backends/hip-ref/ceed-hip-ref-vector.c
  backends/opt/ceed-opt-tensor.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-vector.c
Labels: minor

#850 Slight modifications for hiprtc usage in ROCm 4.5
  backends/hip/ceed-hip-compile.cpp
Labels: minor, 1-In Review, HIP

#876 Small improvements to documentation
  doc/sphinx/source/api/CeedQFunction.rst
  include/ceed/ceed.h
Labels: minor, documentation, 1-In Review

#879 Doxygen cleanup
  Doxyfile
  Makefile
  interface/ceed-preconditioning.c
  interface/ceed.c
Labels: documentation

#882 CI - update to xsmm 1.17
  .gitlab-ci.yml
  backends/xsmm/ceed-xsmm-tensor-f32.c
  backends/xsmm/ceed-xsmm-tensor-f64.c
  backends/xsmm/ceed-xsmm.h
Labels: minor, 1-In Review, CI

#883 basis - handle null pointers to basis matrices
  interface/ceed-basis.c
Labels: minor, 1-In Review
