Repository CEED/libCEED, pull requests merged in 2023-03, with the labels that each got.

#1173 Add CeedOperatorGetContext
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-operator.c
  tests/t525-operator.c
Labels: enhancement, minor, 1-In Review

#1175 Update docstrings for Ceed*ReferenceCopy for clarity
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  interface/ceed-qfunction.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-vector.c
  interface/ceed.c
Labels: documentation, 1-In Review

#1169 Always NULL object on Ceed*Destroy
  examples/fluids/navierstokes.c
  examples/fluids/src/setuplibceed.c
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  interface/ceed-qfunction.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-tensor.c
  interface/ceed-vector.c
  interface/ceed.c
Labels: enhancement, minor, 1-In Review

#1170 Adding CeedVectorCopy() and CeedVectorAXPBY()
  backends/cuda-ref/ceed-cuda-vector.c
  backends/cuda-ref/kernels/cuda-ref-vector.cu
  backends/hip-ref/ceed-hip-ref-vector.c
  backends/hip-ref/kernels/hip-ref-vector.hip.cpp
  include/ceed-impl.h
  include/ceed/ceed.h
  interface/ceed-vector.c
  interface/ceed.c
  python/ceed_vector.py
  python/tests/test-1-vector.py
  rust/libceed/src/vector.rs
  tests/t120-vector.c
  tests/t125-vector.c
  tests/t126-vector.c
Labels: enhancement, 1-In Review

#1174 CeedOperatorContext* -> CeedOperator*Context*
  doc/sphinx/source/releasenotes.md
  examples/fluids/src/dirichlet.c
  examples/fluids/src/misc.c
  examples/fluids/src/setuplibceed.c
  examples/fluids/src/setupts.c
  examples/fluids/src/turb_spanstats.c
  include/ceed/ceed.h
  interface/ceed-operator.c
  tests/t525-operator.c
Labels: interface, 1-In Review

#1177 fluids: Use ContextGetDouble for time and dt label updates
  examples/fluids/navierstokes.h
  examples/fluids/src/setupts.c
Labels: minor, examples, 1-In Review

#1172 Spelling and Ceed example consistency
  Makefile
  backends/cuda-ref/ceed-cuda-ref-basis.c
  backends/hip-ref/ceed-hip-ref-basis.c
  examples/ceed/ex1-volume.c
  examples/ceed/ex1-volume.h
  examples/ceed/ex2-surface.c
  examples/ceed/ex2-surface.h
  interface/ceed-basis.c
  interface/ceed-jit-source-root-default.c
  interface/ceed-jit-source-root-install.c
  interface/ceed-jit-tools.c
  interface/ceed-qfunctioncontext.c
  interface/ceed.c
  rust/libceed/src/basis.rs
  rust/libceed/src/operator.rs
  tests/t001-ceed.c
  tests/t122-vector.c
  tests/t205-elemrestriction.c
  tests/t206-elemrestriction.c
  tests/t207-elemrestriction.c
  tests/t307-basis.c
  tests/t321-basis.c
Labels: minor, 1-In Review

#1179 fix(fluids): Destroy context after call to print_info
  examples/fluids/navierstokes.c
Labels: bug, examples, 1-In Review

#1166 Run Actions or push to main or PR
  .github/workflows/c-fortran-test-hardware.yml
  .github/workflows/c-fortran-test-icc.yml
  .github/workflows/c-fortran-test-linux-osx.yml
  .github/workflows/c-fortran-test-style.yml
  .github/workflows/julia-test-with-style.yml
  .github/workflows/python-test-with-style.yml
  .github/workflows/release-notes.yml
  .github/workflows/rust-documentation.yml
  .github/workflows/rust-test-with-style.yml
  tests/junit.py
Labels: 1-In Review, CI

#1183 fluids/README: a small fix
  examples/fluids/README.md
Labels: documentation, examples

#1178 Add CeedVectorViewRange utility
  include/ceed/ceed.h
  interface/ceed-vector.c
Labels: enhancement, minor, 1-In Review
