Repository CEED/libCEED, pull requests merged in 2023-02, with the labels that each got.

#1152 Support NULL restrict/prolong operators in multigrid
  interface/ceed-preconditioning.c
Labels: enhancement

#1153 Update docstrings for NULL arguments
  interface/ceed-preconditioning.c
Labels: minor, documentation, 1-In Review

#1151 operator: Get OperatorField by field name
  doc/sphinx/source/releasenotes.md
  include/ceed/ceed.h
  interface/ceed-operator.c
Labels: enhancement

#1150 CPU diagonal assembly for multiple active bases
  include/ceed-impl.h
  include/ceed/backend.h
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  tests/t539-operator.c
  tests/t539-operator.h
Labels: bug, enhancement, CPU, 1-In Review

#1155 Prevent duplicate QFunctino/Operator field names
  interface/ceed-qfunction.c
Labels: bug, minor, 1-In Review

#1130 Lift, Drag, Heat Transfer
  examples/fluids/README.md
  examples/fluids/index.md
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/postprocess/vortexshedding.py
  examples/fluids/src/cloptions.c
  examples/fluids/src/setupdm.c
  examples/fluids/src/setupts.c
  examples/fluids/vortexshedding.yaml
Labels: examples, 0-WIP

#1159 memcheck - add vector read/write checking
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/memcheck/ceed-memcheck-blocked.c
  backends/memcheck/ceed-memcheck-serial.c
  backends/memcheck/ceed-memcheck-vector.c
  backends/memcheck/ceed-memcheck.h
  backends/ref/ceed-ref-vector.c
  interface/ceed-preconditioning.c
  interface/ceed-vector.c
Labels: enhancement, 1-In Review

#1161 doc: switch from sphinx-panels (deprecated) to sphinx-design
  doc/sphinx/requirements.txt
  doc/sphinx/source/conf.py
Labels: documentation

#1162 doc: update packages
  .readthedocs.yml
  doc/sphinx/requirements.txt
  doc/sphinx/source/conf.py
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
Labels: documentation

#1147 fluids: Add generic L2 projection function
  examples/fluids/include/matops.h
  examples/fluids/navierstokes.h
  examples/fluids/src/dirichlet.c
  examples/fluids/src/matops.c
  examples/fluids/src/misc.c
  examples/fluids/src/setupts.c
  examples/fluids/src/turb_spanstats.c
Labels: enhancement, examples, 1-In Review
