Repository CEED/libCEED, pull requests merged in 2023-07, with the labels that each got.

#1244 Minor whitespace consistency fixes in backends
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-ref/ceed-cuda-ref-restriction.c
  backends/cuda-ref/ceed-cuda-ref-vector.c
  backends/hip-ref/ceed-hip-ref-vector.c
  backends/hip-ref/ceed-hip-ref.h
  backends/sycl-ref/ceed-sycl-ref-basis.sycl.cpp
  backends/sycl-ref/ceed-sycl-ref-qfunction-load.sycl.cpp
  backends/sycl-ref/ceed-sycl-ref-qfunction.sycl.cpp
  backends/sycl-ref/ceed-sycl-ref-qfunctioncontext.sycl.cpp
  backends/sycl-ref/ceed-sycl-ref.sycl.cpp
  backends/sycl-ref/ceed-sycl-vector.sycl.cpp
  backends/sycl-shared/ceed-sycl-shared-basis.sycl.cpp
  backends/sycl-shared/ceed-sycl-shared.sycl.cpp
  include/ceed/jit-source/sycl/sycl-ref-qfunction.h
Labels: minor

#1246 Fix a few missing default output/messages for junit/tap
  tests/junit.py
Labels: testing

#1249 Memcheck - warn or error on NaN after write-only access
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-qfunction.c
  backends/cuda-ref/ceed-cuda-ref-basis.c
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/cuda-ref/ceed-cuda-ref-qfunction-load.cpp
  backends/cuda-ref/ceed-cuda-ref-qfunction.c
  backends/cuda-ref/ceed-cuda-ref-restriction.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-qfunction.c
  backends/hip-ref/ceed-hip-ref-basis.c
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/hip-ref/ceed-hip-ref-qfunction-load.cpp
  backends/hip-ref/ceed-hip-ref-qfunction.c
  backends/hip-ref/ceed-hip-ref-restriction.c
  backends/hip-shared/ceed-hip-shared-basis.c
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma-restriction.c
  backends/memcheck/ceed-memcheck-qfunction.c
  backends/memcheck/ceed-memcheck-vector.c
  backends/memcheck/ceed-memcheck.h
  backends/sycl-ref/ceed-sycl-ref-qfunction-load.sycl.cpp
  backends/sycl-shared/ceed-sycl-shared-basis.sycl.cpp
  backends/sycl/online_compiler.hpp
  doc/sphinx/source/api/backend/Ceed.rst
  include/ceed/backend.h
  interface/ceed-jit-tools.c
  interface/ceed-preconditioning.c
  interface/ceed.c
Labels: enhancement, minor, 1-In Review

#1253 README fixes
  README.md
Labels: minor, documentation, 1-In Review

#1164 Basis Eval at arbitrary points
  include/ceed-impl.h
  include/ceed/ceed.h
  interface/ceed-basis.c
  interface/ceed.c
  tests/README.md
  tests/t311-basis.c
  tests/t313-basis.c
  tests/t350-basis.c
  tests/t351-basis.c
  tests/t352-basis.c
  tests/t353-basis.c
  tests/t354-basis.c
Labels: enhancement, design, 1-In Review

#1247 fluids: Add partition statistics to standard output
  examples/fluids/include/petsc_ops.h
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/src/misc.c
Labels: enhancement, examples

#1261 ci: Fix ifort configuration
  .github/workflows/c-fortran-test-icc.yml
Labels: 1-In Review, CI

#1260 fluids: Don't show partition stats for serial jobs
  examples/fluids/src/misc.c
Labels: examples, 1-In Review

#1257 fluids: Remove ComputeL2Projection function
  examples/fluids/navierstokes.h
  examples/fluids/src/misc.c
Labels: enhancement, examples, 1-In Review

#1263 Change os.path to pathlib and simplify parsing
  tests/junit.py
Labels: CI, style

#1266 fluids: Fix mem leaks in grid_anisotropy_tensor.c
  examples/fluids/src/grid_anisotropy_tensor.c
Labels: examples, 1-In Review

#1269 Check for compatible num_qpts with CEED_BASIS_COLLOCATED
  examples/fluids/problems/sgs_dd_model.c
  examples/fluids/qfunctions/stg_shur14.h
  examples/fluids/src/grid_anisotropy_tensor.c
  examples/fluids/src/setuplibceed.c
  examples/fluids/src/strong_boundary_conditions.c
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  rust/libceed/src/operator.rs
  rust/libceed/src/vector.rs
  tests/t509-operator.c
Labels: enhancement, examples, 1-In Review
