Repository CEED/libCEED, pull requests merged in 2023-10, with the labels that each got.

#1358 chore: Fix format.ch command to grab all files
  Makefile
Labels: minor, building, 1-In Review, style

#1357 docs: Clarify QFunction source compatability
  interface/ceed-qfunction.c
Labels: documentation, 1-In Review

#1360 Remove unused parameter from CeedTensorContractCreate
  backends/avx/ceed-avx-tensor.c
  backends/avx/ceed-avx.h
  backends/opt/ceed-opt-tensor.c
  backends/opt/ceed-opt.h
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-tensor.c
  backends/ref/ceed-ref.h
  backends/xsmm/ceed-xsmm-tensor.c
  backends/xsmm/ceed-xsmm.h
  include/ceed-impl.h
  include/ceed/backend.h
  interface/ceed-tensor.c
  julia/LibCEED.jl/src/generated/libceed_bindings.jl
Labels: interface

#1362 Update Delegation/Fallback Docs + CPU Usage
  backends/blocked/ceed-blocked.c
  backends/opt/ceed-opt-blocked.c
  backends/opt/ceed-opt-serial.c
  doc/sphinx/source/libCEEDdev.md
Labels: bug, documentation, 1-In Review

#1364 Update CeedContextFieldLabelGetDescription with offset
  include/ceed/ceed.h
  interface/ceed-qfunctioncontext.c
  tests/t407-qfunction.c
Labels: interface, 1-In Review

#1359 Improve CPU-based operator full assembly by using optimized backend tensor contraction
  Makefile
  backends/blocked/ceed-blocked-operator.c
  backends/opt/ceed-opt-operator.c
  interface/ceed-preconditioning.c
Labels: enhancement, CPU, 1-In Review

#1367 Flag assembly data as stale if ctx data changed
  interface/ceed-operator.c
Labels: minor, 1-In Review

#1369 chore: make info returns actual flags
  Makefile
Labels: minor, building, 1-In Review

#1368 Fix compiler vendor detection for `cc`
  Makefile
Labels: bug, minor, building, 1-In Review

#1330 fluids: Add StatePhysicalGradientFromReference util
  examples/fluids/blasius.yaml
  examples/fluids/qfunctions/freestream_bc.h
  examples/fluids/qfunctions/newtonian.h
  examples/fluids/qfunctions/newtonian_state.h
Labels: examples, 1-In Review

#1372 Add parallelism within test files
  .gitlab-ci.yml
  Makefile
  tests/junit.py
  tests/junit_common.py
Labels: testing, 1-In Review

#1374 fix(test): Use explicit `typing` objects for containers
  tests/junit.py
  tests/junit_common.py
Labels: testing, 1-In Review

#1376 Improve TAP output
  tests/junit_common.py
Labels: testing, 1-In Review

#1377 Rust - clearer t501 error message
  rust/libceed/src/lib.rs
Labels: minor, 1-In Review, Rust

#1379 fluids: Don't set ts_max_steps if not TESTTYPE_NONE
  examples/fluids/navierstokes.c
  examples/fluids/src/setupts.c
Labels: examples, 1-In Review

#1382 Lazy RTC compilation of MAGMA basis kernels for small P, Q
  Makefile
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma-common.c
  backends/magma/ceed-magma-gemm-nontensor.cpp
  backends/magma/ceed-magma-gemm-nontensor.h
  backends/magma/ceed-magma-gemm-selector.cpp
  backends/magma/ceed-magma-gemm-selector.h
  backends/magma/ceed-magma.h
  backends/magma/gemm_selector.cpp
  backends/magma/kernels/common/weight.h
  backends/magma/kernels/cuda/weight_generic.cu
  backends/magma/kernels/hip/weight_generic.hip.cpp
  backends/magma/tuning/a100.h
  backends/magma/tuning/a100_grad_rtc.h
  backends/magma/tuning/a100_interp_rtc.h
  backends/magma/tuning/indices.h
  backends/magma/tuning/mi100.h
  backends/magma/tuning/mi250x.h
  backends/magma/tuning/mi250x_grad_rtc.h
  backends/magma/tuning/mi250x_interp_rtc.h
  backends/magma/tuning/v100.h
  backends/magma/tuning/v100_rtc-b.h
  backends/magma/tuning/v100_rtc-new.h
  include/ceed/jit-source/magma/grad-1d.h
  include/ceed/jit-source/magma/grad-2d.h
  include/ceed/jit-source/magma/grad-3d.h
  include/ceed/jit-source/magma/grad-nontensor.h
  include/ceed/jit-source/magma/interp-1d.h
  include/ceed/jit-source/magma/interp-2d.h
  include/ceed/jit-source/magma/interp-3d.h
  include/ceed/jit-source/magma/interp-nontensor.h
  include/ceed/jit-source/magma/magma-basis-grad-1d.h
  include/ceed/jit-source/magma/magma-basis-grad-2d.h
  include/ceed/jit-source/magma/magma-basis-grad-3d.h
  include/ceed/jit-source/magma/magma-basis-grad-nontensor.h
  include/ceed/jit-source/magma/magma-basis-interp-1d.h
  include/ceed/jit-source/magma/magma-basis-interp-2d.h
  include/ceed/jit-source/magma/magma-basis-interp-3d.h
  include/ceed/jit-source/magma/magma-basis-interp-nontensor.h
  include/ceed/jit-source/magma/magma-basis-weight-1d.h
  include/ceed/jit-source/magma/magma-basis-weight-2d.h
  include/ceed/jit-source/magma/magma-basis-weight-3d.h
  include/ceed/jit-source/magma/magma-basis-weight-nontensor.h
  include/ceed/jit-source/magma/magma-common-defs.h
  include/ceed/jit-source/magma/magma-common-nontensor.h
  include/ceed/jit-source/magma/magma-common-tensor.h
  include/ceed/jit-source/magma/magma_common_nontensor.h
  include/ceed/jit-source/magma/magma_common_tensor.h
Labels: GPU, MAGMA, 1-In Review

#1383 Remove accidental WIP tuning files from #1382
  backends/magma/tuning/v100_rtc-b.h
  backends/magma/tuning/v100_rtc-new.h
Labels: minor

#1387 Fix Python tests in GitHub Actions
  requirements-test.txt
Labels: minor, CI

#1388 Add support for `CEED_EVAL_GRADIENT` and `CEED_TRANSPOSE` in `CeedBasisApplyAtPoints`
  interface/ceed-basis.c
  tests/t357-basis.c
Labels: interface, 1-In Review
