Repository CEED/libCEED, pull requests merged in 2023-05, with the labels that each got.

#1207 Fix make info alignment
  Makefile
Labels: minor, 1-In Review

#1208 Remove unused variable in libCEED examples
  examples/ceed/ex1-volume.c
  examples/ceed/ex2-surface.c
Labels: minor, 1-In Review

#1210 Fix bug in `CeedBasisCreateProjectionMatrices` for non-H^1 basis
  interface/ceed-basis.c
Labels: bug

#1211 Fix OperatorApply Bug
  interface/ceed-operator.c
Labels: bug, 1-In Review

#1215 doc: update to altair-5.0 and sphinext-altair
  doc/sphinx/requirements.txt
  doc/sphinx/source/conf.py
  examples/solids/index.md
Labels: documentation

#1213 Consistency with Ceed*Refrence and Ceed*ReferenceCopy
  backends/blocked/ceed-blocked-operator.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-operator.c
  include/ceed/backend.h
  interface/ceed-basis.c
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed-qfunction.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-tensor.c
  interface/ceed-vector.c
  julia/LibCEED.jl/src/generated/libceed_bindings.jl
Labels: minor, 1-In Review

#1149 fluids: Data-driven SGS modeling
  doc/sphinx/source/references.bib
  examples/fluids/README.md
  examples/fluids/dd_sgs_data/OutScaling.dat
  examples/fluids/dd_sgs_data/b1.dat
  examples/fluids/dd_sgs_data/b2.dat
  examples/fluids/dd_sgs_data/w1.dat
  examples/fluids/dd_sgs_data/w2.dat
  examples/fluids/include/petsc_ops.h
  examples/fluids/index.md
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/sgs_dd_model.c
  examples/fluids/problems/stg_shur14.c
  examples/fluids/qfunctions/freestream_bc.h
  examples/fluids/qfunctions/grid_anisotropy_tensor.h
  examples/fluids/qfunctions/mass.h
  examples/fluids/qfunctions/newtonian.h
  examples/fluids/qfunctions/newtonian_state.h
  examples/fluids/qfunctions/sgs_dd_model.h
  examples/fluids/qfunctions/utils.h
  examples/fluids/qfunctions/utils_eigensolver_jacobi.h
  examples/fluids/qfunctions/velocity_gradient_projection.h
  examples/fluids/src/cloptions.c
  examples/fluids/src/grid_anisotropy_tensor.c
  examples/fluids/src/matops.c
  examples/fluids/src/misc.c
  examples/fluids/src/petsc_ops.c
  examples/fluids/src/setuplibceed.c
  examples/fluids/src/setupts.c
  examples/fluids/src/turb_spanstats.c
  examples/fluids/src/velocity_gradient_projection.c
  examples/fluids/tests-output/fluids-navierstokes-blasius-sgs-data-driven.bin
  include/ceed/types.h
Labels: examples, 1-In Review

#1185 fluids: Move to local Vec storage and petsc-ops
  examples/fluids/include/petsc_ops.h
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/blasius.c
  examples/fluids/problems/newtonian.c
  examples/fluids/problems/stg_shur14.c
  examples/fluids/qfunctions/freestream_bc.h
  examples/fluids/qfunctions/strong_boundary_conditions.h
  examples/fluids/src/cloptions.c
  examples/fluids/src/grid_anisotropy_tensor.c
  examples/fluids/src/misc.c
  examples/fluids/src/petsc_ops.c
  examples/fluids/src/setupdm.c
  examples/fluids/src/setuplibceed.c
  examples/fluids/src/setupts.c
  examples/fluids/src/strong_boundary_conditions.c
  examples/fluids/src/turb_spanstats.c
  examples/fluids/src/velocity_gradient_projection.c
Labels: enhancement, examples, 1-In Review

#1212 ASAN Fixes
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
  interface/ceed-preconditioning.c
  tests/t530-operator.c
  tests/t531-operator.c
  tests/t532-operator.c
  tests/t537-operator.c
  tests/t538-operator.c
  tests/t539-operator.c
Labels: bug, minor, 1-In Review

#1216 Error in CI on clang-tidy errors
  .clang-tidy
  .gitlab-ci.yml
Labels: bug, 1-In Review, CI

#1218 ci: update to rocm-5.5
  .gitlab-ci.yml
Labels: CI

#1221 No ctx access after restoring
  interface/ceed-qfunction.c
Labels: bug, minor, 1-In Review

#1222 style(fluids): Misc typo fixes
  examples/fluids/blasius.yaml
  examples/fluids/problems/blasius.c
  examples/fluids/problems/sgs_dd_model.c
  examples/fluids/problems/stg_shur14.c
Labels: minor, examples, 1-In Review
