Repository CEED/libCEED, pull requests merged in 2023-12, with the labels that each got.

#1411 Update petsc-dmswarm example to use CeedOperatorAtPoints
  examples/petsc/dmswarm.c
  examples/petsc/include/petscutils.h
  examples/petsc/include/swarmutils.h
  examples/petsc/qfunctions/swarm/swarmmass.h
  examples/petsc/src/petscutils.c
  examples/petsc/src/swarmutils.c
Labels: examples, 1-In Review

#1412 Update PETSc examples to use VecP2C and VecC2P
  examples/petsc/area.c
  examples/petsc/bps.c
  examples/petsc/bpsraw.c
  examples/petsc/bpssphere.c
  examples/petsc/multigrid.c
  examples/petsc/src/libceedsetup.c
  examples/petsc/src/matops.c
Labels: examples, 1-In Review

#1413 Formatting and comment improvements for PETSc examples
  examples/petsc/bpsraw.c
  examples/petsc/dmswarm.c
  examples/petsc/include/areaproblemdata.h
  examples/petsc/include/bpsproblemdata.h
  examples/petsc/include/libceedsetup.h
  examples/petsc/include/matops.h
  examples/petsc/include/petscutils.h
  examples/petsc/include/petscversion.h
  examples/petsc/include/sphereproblemdata.h
  examples/petsc/include/structs.h
  examples/petsc/qfunctions/swarm/swarmmass.h
  examples/petsc/src/libceedsetup.c
  examples/petsc/src/matops.c
  examples/petsc/src/petscutils.c
  examples/petsc/src/swarmutils.c
Labels: minor, examples, PETSc, 1-In Review

#1409 Docstring consistency
  .clang-format
  gallery/ceed-gallery-list.h
  gallery/identity/ceed-identity.c
  gallery/mass-vector/ceed-vectormassapply.c
  gallery/mass/ceed-mass1dbuild.c
  gallery/mass/ceed-mass2dbuild.c
  gallery/mass/ceed-mass3dbuild.c
  gallery/mass/ceed-massapply.c
  gallery/poisson-vector/ceed-vectorpoisson1dapply.c
  gallery/poisson-vector/ceed-vectorpoisson2dapply.c
  gallery/poisson-vector/ceed-vectorpoisson3dapply.c
  gallery/poisson/ceed-poisson1dapply.c
  gallery/poisson/ceed-poisson1dbuild.c
  gallery/poisson/ceed-poisson2dapply.c
  gallery/poisson/ceed-poisson2dbuild.c
  gallery/poisson/ceed-poisson3dapply.c
  gallery/poisson/ceed-poisson3dbuild.c
  gallery/scale/ceed-scale.c
  include/ceed-impl.h
  include/ceed/ceed.h
  interface/ceed-basis.c
  interface/ceed-cuda.c
  interface/ceed-elemrestriction.c
  interface/ceed-hip.c
  interface/ceed-jit-tools.c
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  interface/ceed-qfunction-register.c
  interface/ceed-qfunction.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-register.c
  interface/ceed-tensor.c
  interface/ceed-vector.c
  interface/ceed.c
Labels: minor, documentation, 1-In Review

#1414 Add support for running BPs with integration at particle points
  examples/petsc/.gitignore
  examples/petsc/Makefile
  examples/petsc/bpsswarm.c
  examples/petsc/dmswarm.c
  examples/petsc/include/libceedsetup.h
  examples/petsc/include/swarmutils.h
  examples/petsc/src/libceedsetup.c
  examples/petsc/src/matops.c
  examples/petsc/src/swarmutils.c
Labels: examples, PETSc, 1-In Review

#1421 Fix op swarm input access
  backends/ref/ceed-ref-operator.c
Labels: bug, 1-In Review

#1423 fluids: Support higher-order geometry
  examples/fluids/src/dm_utils.c
  examples/fluids/src/setupdm.c
Labels: examples, 1-In Review

#1424 Minor function signature fix caught with ASan
  backends/ref/ceed-ref-vector.c
Labels: minor, 1-In Review

#1425 Consistency fix for a few missed CeedElemRestriction and CeedBasis variable names in the public API
  include/ceed/ceed.h
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
Labels: minor, 1-In Review

#1426 Fix trailing spaces in non-linted files
  CONTRIBUTING.md
  Makefile
  doc/sphinx/source/libCEEDapi.md
  doc/sphinx/source/precision.md
  doc/sphinx/source/releasenotes.md
  examples/petsc/README.md
  tests/README.md
  tests/t208-elemrestriction-f.f90
  tests/t314-basis-f.f90
  tests/t320-basis-f.f90
  tests/t322-basis-f.f90
  tests/t323-basis-f.f90
  tests/t400-qfunction-f.f90
  tests/t401-qfunction-f.f90
  tests/t402-qfunction-f.f90
  tests/t500-operator-f.f90
  tests/t501-operator-f.f90
  tests/t502-operator-f.f90
  tests/t503-operator-f.f90
  tests/t504-operator-f.f90
  tests/t505-operator-f.f90
  tests/t506-operator-f.f90
  tests/t510-operator-f.f90
  tests/t511-operator-f.f90
  tests/t520-operator-f.f90
  tests/t521-operator-f.f90
  tests/t522-operator-f.f90
  tests/t523-operator-f.f90
  tests/t524-operator-f.f90
  tests/t530-operator-f.f90
  tests/t531-operator-f.f90
  tests/t532-operator-f.f90
  tests/t533-operator-f.f90
  tests/t534-operator-f.f90
  tests/t535-operator-f.f90
  tests/t536-operator-f.f90
  tests/t540-operator-f.f90
  tests/t550-operator-f.f90
  tests/t552-operator-f.f90
Labels: minor, 1-In Review

#1427 Add gpu dev notes
  doc/sphinx/source/gpu.md
  doc/sphinx/source/index.md
Labels: documentation, 1-In Review

#1433 Remove atomic adds from `CeedElemRestrictionApplyStridedTranspose`
  backends/ref/ceed-ref-restriction.c
Labels: minor, performance, 1-In Review

#1435 GPU - Avoid calling diagonal assembly kernels if input arrays are null pointers
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
Labels: bug, GPU, CUDA, 1-In Review, HIP
