Repository CEED/libCEED, pull requests merged in 2023-09, with the labels that each got.

#1322 Fix a few header includes following PR #1320
  backends/sycl-gen/ceed-sycl-gen-operator-build.hpp
  backends/sycl-gen/ceed-sycl-gen.hpp
  backends/sycl-ref/ceed-sycl-ref-qfunction-load.hpp
  backends/sycl-ref/ceed-sycl-ref.hpp
  backends/sycl-shared/ceed-sycl-shared.hpp
  backends/sycl/ceed-sycl-common.hpp
  backends/sycl/ceed-sycl-compile.hpp
  backends/xsmm/ceed-xsmm.h
Labels: minor

#1324 Fix order of tensor contractions for `CeedBasisApplyAtPoints`
  interface/ceed-basis.c
  tests/t350-basis.c
  tests/t351-basis.c
  tests/t352-basis.c
  tests/t353-basis.c
  tests/t354-basis.c
  tests/t355-basis.c
  tests/t356-basis.c
Labels: bug, testing

#1325 Change coordinate ordering to be consistent with tensor basis application
  tests/t313-basis-f.f90
  tests/t313-basis.c
  tests/t314-basis-f.f90
  tests/t314-basis.c
  tests/t315-basis.c
  tests/t316-basis.c
  tests/t318-basis.c
  tests/t319-basis.c
Labels: bug, testing, 1-In Review

#1317 Update clang-format version to v16
  .github/workflows/c-fortran-test-style.yml
  interface/ceed.c
Labels: minor, 1-In Review

#1321 gpu - fix SetArray on device logic bug
  backends/cuda-ref/ceed-cuda-ref-vector.c
  backends/hip-ref/ceed-hip-ref-vector.c
  backends/sycl-ref/ceed-sycl-vector.sycl.cpp
Labels: bug, GPU, 1-In Review

#1327 Fix for `make PEDANTIC=1 prove`
  tests/t570-operator.h
Labels: minor, testing, 1-In Review

#1329 fluids: Add qdata packing/unpacking helpers
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/blasius.h
  examples/fluids/qfunctions/channel.h
  examples/fluids/qfunctions/differential_filter.h
  examples/fluids/qfunctions/eulervortex.h
  examples/fluids/qfunctions/freestream_bc.h
  examples/fluids/qfunctions/newtonian.h
  examples/fluids/qfunctions/setupgeo.h
  examples/fluids/qfunctions/sgs_dd_model.h
  examples/fluids/qfunctions/shocktube.h
  examples/fluids/qfunctions/stg_shur14.h
  examples/fluids/qfunctions/utils.h
  examples/fluids/qfunctions/velocity_gradient_projection.h
Labels: examples, 1-In Review

#1233 Add CeedOperatorLinearAssemblePointBlockDiagonalSymbolic
  doc/sphinx/source/releasenotes.md
  examples/fluids/navierstokes.c
  examples/fluids/src/setupts.c
  examples/fluids/tests-output/fluids-navierstokes-gaussianwave-shell.bin
  include/ceed/ceed.h
  interface/ceed-preconditioning.c
  tests/t537-operator.c
Labels: enhancement, interface, 1-In Review

#1332 junit - remove walrus for old systems
  tests/junit_common.py
Labels: minor, testing, 1-In Review

#1334 Add Missing CeedCallBackends
  backends/ref/ceed-ref-restriction.c
Labels: bug, minor, 1-In Review

#1336 Tiny fix to include order for test `t406`
  tests/t406-qfunction.h
Labels: minor, 1-In Review

#1335 Fix some missing backend consistency from #1315
  .clang-format
  backends/cuda-ref/ceed-cuda-ref-vector.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/hip-ref/ceed-hip-ref-vector.c
  backends/hip-shared/ceed-hip-shared-basis.c
  backends/occa/ceed-occa-basis.hpp
  backends/occa/ceed-occa-context.cpp
  backends/occa/ceed-occa-context.hpp
  backends/occa/ceed-occa-operator-args.cpp
  backends/occa/ceed-occa-operator-args.hpp
  backends/occa/ceed-occa-qfunction-args.cpp
  backends/occa/ceed-occa-qfunction-args.hpp
  backends/occa/ceed-occa-types.hpp
  backends/occa/kernels/set-value.cpp
  backends/sycl-ref/ceed-sycl-ref-basis.sycl.cpp
  backends/sycl-ref/ceed-sycl-ref-qfunction-load.sycl.cpp
  backends/sycl-ref/ceed-sycl-vector.sycl.cpp
  include/ceed/backend.h
  include/ceed/jit-source/cuda/cuda-gen-templates.h
  include/ceed/jit-source/cuda/cuda-jit.h
  include/ceed/jit-source/cuda/cuda-ref-basis-tensor.h
  include/ceed/jit-source/cuda/cuda-ref-qfunction.h
  include/ceed/jit-source/cuda/cuda-types.h
  include/ceed/jit-source/hip/hip-gen-templates.h
  include/ceed/jit-source/hip/hip-ref-basis-tensor.h
  include/ceed/jit-source/hip/hip-ref-qfunction.h
  include/ceed/jit-source/hip/hip-shared-basis-read-write-templates.h
  include/ceed/jit-source/hip/hip-types.h
  include/ceed/jit-source/magma/grad-1d.h
  include/ceed/jit-source/magma/grad-3d.h
  include/ceed/jit-source/magma/grad-nontensor.h
  include/ceed/jit-source/magma/interp-1d.h
  include/ceed/jit-source/magma/interp-2d.h
  include/ceed/jit-source/magma/interp-3d.h
  include/ceed/jit-source/magma/interp-nontensor.h
  include/ceed/jit-source/magma/magma_common_nontensor.h
  include/ceed/jit-source/magma/magma_common_tensor.h
  include/ceed/jit-source/magma/weight-1d.h
  include/ceed/jit-source/magma/weight-2d.h
  include/ceed/jit-source/magma/weight-3d.h
  include/ceed/jit-source/sycl/sycl-gen-templates.h
  include/ceed/jit-source/sycl/sycl-shared-basis-read-write-templates.h
  include/ceed/jit-source/sycl/sycl-shared-basis-tensor.h
  include/ceed/jit-source/sycl/sycl-types.h
  interface/ceed-preconditioning.c
  interface/ceed-qfunctioncontext.c
  interface/ceed-vector.c
  interface/ceed.c
Labels: minor, 1-In Review

#1337 fluids: Change variable name "local" to appease ocloc
  examples/fluids/qfunctions/utils.h
Labels: bug, examples, 1-In Review

#1338 fluids: Use explicit array size for `new_bounds`
  examples/fluids/qfunctions/sgs_dd_model.h
  examples/fluids/qfunctions/sgs_dd_utils.h
Labels: minor, examples, 1-In Review

#1333 Add ElemRestrictionAtPoints
  backends/blocked/ceed-blocked-operator.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-restriction.c
  backends/ref/ceed-ref.c
  include/ceed-impl.h
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-elemrestriction.c
  interface/ceed-operator.c
  interface/ceed.c
  tests/output/t230-elemrestriction.out
  tests/t230-elemrestriction.c
  tests/t231-elemrestriction.c
  tests/t232-elemrestriction.c
  tests/t233-elemrestriction.c
Labels: interface, CPU, 1-In Review

#1279 Support CPU shared-memory parallelism with OpenMP
  .github/workflows/c-fortran-test-icc.sh
  Makefile
  README.md
  backends/ceed-backend-weak.c
  backends/ref/ceed-ref-restriction.c
  doc/sphinx/source/releasenotes.md
  include/ceed/backend.h
  interface/ceed-qfunction-register.c
  interface/ceed-qfunction.c
  interface/ceed-register.c
  interface/ceed.c
Labels: enhancement, CPU, 1-In Review

#1339 Spelling is hard
  doc/sphinx/source/libCEEDapi.md
  doc/sphinx/source/libCEEDdev.md
  doc/sphinx/source/releasenotes.md
  examples/petsc/qfunctions/area/areacube.h
  interface/ceed-basis.c
  interface/ceed-operator.c
  interface/ceed-qfunction-register.c
  interface/ceed-register.c
  interface/ceed.c
  tests/t101-vector.c
  tests/t105-vector.c
  tests/t203-elemrestriction.c
  tests/t204-elemrestriction.c
  tests/t208-elemrestriction-f.f90
  tests/t208-elemrestriction.c
  tests/t209-elemrestriction.c
  tests/t213-elemrestriction.c
  tests/t300-basis.c
  tests/t307-basis.c
  tests/t320-basis-f.h
  tests/t330-basis.h
  tests/t356-basis.c
  tests/t406-qfunction-scales.h
  tests/t507-operator.c
  tests/t553-operator.c
Labels: minor

#1316 Non-square operator full assembly
  backends/blocked/ceed-blocked-operator.c
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/cuda-ref/ceed-cuda-ref.h
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-operator.c
  backends/sycl-ref/ceed-sycl-ref-operator.sycl.cpp
  include/ceed-impl.h
  include/ceed/backend.h
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  tests/README.md
  tests/t509-operator.c
  tests/t523-operator.c
  tests/t539-operator.c
  tests/t560-operator.c
  tests/t561-operator.c
  tests/t562-operator.c
  tests/t563-operator.c
  tests/t564-operator.c
  tests/t565-operator.c
  tests/t566-operator.c
  tests/t567-operator.c
  tests/t568-operator.c
  tests/t569-operator.c
  tests/t570-operator.c
  tests/t580-operator.c
  tests/t580-operator.h
  tests/t581-operator.c
  tests/t582-operator.c
  tests/t583-operator.c
Labels: bug, 1-In Review

#1340 Fix CEED_COPY_VALUES for ref rstr at points
  backends/ref/ceed-ref-restriction.c
  include/ceed/backend.h
  include/ceed/ceed.h
  interface/ceed-elemrestriction.c
  tests/t233-elemrestriction.c
Labels: bug, 1-In Review

#1341 Avoid VLA for assembled element matrices in `CeedSingleOperatorAssemble`
  interface/ceed-preconditioning.c
Labels: minor, CPU

#1344 Fix regression in multiple active bases diagonal assembly (alternative to #1343)
  interface/ceed-preconditioning.c
Labels: bug, 1-In Review

#1345 fluids: Add ASAN, Correct memory out-of-bounds error
  examples/fluids/Makefile
  examples/fluids/qfunctions/grid_anisotropy_tensor.h
  examples/fluids/qfunctions/utils_eigensolver_jacobi.h
Labels: examples, 1-In Review

#1347 ctx - only update in CeedQFunctionContextSet* when data is different
  interface/ceed-qfunctioncontext.c
Labels: minor, performance, 1-In Review

#1348 fluids: Fix 64bit Int typing issues
  examples/fluids/navierstokes.h
  examples/fluids/src/differential_filter.c
  examples/fluids/src/dm_utils.c
Labels: minor, examples, 1-In Review

#1349 fluids: Use normal `CeedOperatorSetContextDouble` instead of `UpdateContextLabel`
  examples/fluids/src/setupts.c
Labels: minor, examples, 1-In Review

#1284 DMSwarm Example with Interpolation and Projection
  .gitignore
  examples/petsc/.gitignore
  examples/petsc/Makefile
  examples/petsc/dmswarm.c
Labels: examples, 1-In Review

#1350 fix(fluids): Don't use IntArrayC2P in diff filter
  examples/fluids/src/differential_filter.c
Labels: examples, 1-In Review

#1310 Remove CeedOperatorSetNumQuadraturePoints
  doc/sphinx/source/releasenotes.md
  include/ceed/ceed.h
  interface/ceed-operator.c
  interface/ceed-preconditioning.c
  julia/LibCEED.jl/src/generated/libceed_bindings.jl
Labels: minor, 1-In Review

#1353 CodeCov Fixes
  backends/memcheck/ceed-memcheck-qfunctioncontext.c
  backends/memcheck/ceed-memcheck-vector.c
  backends/ref/ceed-ref-qfunctioncontext.c
  backends/ref/ceed-ref-restriction.c
  backends/ref/ceed-ref-vector.c
  interface/ceed-jit-tools.c
  interface/ceed.c
  tests/t217-elemrestriction.c
  tests/t218-elemrestriction.c
  tests/t219-elemrestriction.c
  tests/t231-elemrestriction.c
  tests/t232-elemrestriction.c
  tests/t233-elemrestriction.c
  tests/t406-qfunction.c
  tests/t408-qfunction.c
  tests/t501-operator.c
Labels: minor, 1-In Review, CI

#1354 Magma make tidy fixes
  backends/magma/gemm_selector.cpp
  backends/magma/magma_gemm_nontensor.c
Labels: minor, 1-In Review
