Repository CEED/libCEED, pull requests merged in 2024-01, with the labels that each got.

#1431 Silence compiler warning for `-Wstrict-prototypes`
  include/ceed/backend.h
  interface/ceed-qfunction-register.c
  interface/ceed-register.c
  interface/ceed.c
Labels: minor, building, 1-In Review

#1432 Define CeedPragmaSIMD for Clang
  include/ceed/types.h
Labels: minor, building, 1-In Review

#1438 Add __restrict__ to resolve vectorization warnings with Clang 17
  backends/ref/ceed-ref-restriction.c
Labels: minor, performance, 1-In Review

#1439 Add missing magma_finialize() call
  backends/magma/ceed-magma-common.c
Labels: bug, minor, 1-In Review

#1440 Fix CeedVectorAXPBY Implementations
  backends/cuda-ref/ceed-cuda-ref-vector.c
  backends/hip-ref/ceed-hip-ref-vector.c
  interface/ceed-vector.c
  python/tests/test-1-vector.py
  rust/libceed/src/vector.rs
  tests/t125-vector.c
Labels: bug, 1-In Review

#1418 memcheck - match nan check for QFunction field size
  backends/memcheck/ceed-memcheck-qfunction.c
Labels: minor, 1-In Review

#1428 Remove legacy CEED_BASIS_COLLOCATED
  doc/img/libceed_schematic_op_setup_mass.svg
  doc/sphinx/source/releasenotes.md
  examples/fluids/src/smartsim/sgs_dd_training.c
  examples/python/tutorial-5-operator.ipynb
  include/ceed/ceed.h
  interface/ceed-basis.c
  interface/ceed-fortran.c
  julia/LibCEED.jl/src/C.jl
  python/__init__.py
Labels: interface, 1-In Review

#1302 GPU element restriction for `CEED_RESTRICTION_ORIENTED` and `CEED_RESTRICTION_CURL_ORIENTED`
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/cuda-ref/ceed-cuda-ref-restriction.c
  backends/cuda-ref/ceed-cuda-ref.h
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/hip-ref/ceed-hip-ref-restriction.c
  backends/hip-ref/ceed-hip-ref.h
  backends/ref/ceed-ref-restriction.c
  backends/sycl-ref/ceed-sycl-ref-operator.sycl.cpp
  backends/sycl-ref/ceed-sycl-ref.hpp
  backends/sycl-ref/ceed-sycl-restriction.sycl.cpp
  include/ceed/backend.h
  include/ceed/jit-source/cuda/cuda-ref-operator-assemble-diagonal.h
  include/ceed/jit-source/cuda/cuda-ref-operator-assemble.h
  include/ceed/jit-source/cuda/cuda-ref-restriction.h
  include/ceed/jit-source/hip/hip-ref-operator-assemble-diagonal.h
  include/ceed/jit-source/hip/hip-ref-operator-assemble.h
  include/ceed/jit-source/hip/hip-ref-restriction.h
  interface/ceed-preconditioning.c
Labels: GPU, 1-In Review

#1444 memcheck: Add QF path and name to error message
  backends/memcheck/ceed-memcheck-qfunction.c
Labels: minor, backend, 1-In Review

#1445 fluids: Add cosine hill and skewed advection initial conditions
  examples/fluids/README.md
  examples/fluids/advection.yaml
  examples/fluids/navierstokes.c
  examples/fluids/navierstokes.h
  examples/fluids/problems/advection.c
  examples/fluids/qfunctions/advection.h
  examples/fluids/qfunctions/advection_types.h
  examples/fluids/qfunctions/shocktube.h
  examples/fluids/tests-output/fluids-navierstokes-adv-rotation-cosine.bin
  examples/fluids/tests-output/fluids-navierstokes-adv-skew.bin
Labels: examples, 1-In Review

#1451 rust - drop failing tests
  rust/libceed/src/operator.rs
Labels: bug, 1-In Review, Rust

#1449 Improve vectorization for CPU curl-oriented element restriction transpose
  backends/ref/ceed-ref-restriction.c
  interface/ceed-elemrestriction.c
Labels: enhancement, minor, performance, 1-In Review

#1450 Refactoring to speed up GPU kernel JIT compilation
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/cuda-ref/ceed-cuda-ref-restriction.c
  backends/cuda-ref/ceed-cuda-ref.h
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/hip-ref/ceed-hip-ref-restriction.c
  backends/hip-ref/ceed-hip-ref.h
  backends/magma/ceed-magma-basis.c
  backends/magma/ceed-magma.h
  include/ceed/jit-source/cuda/cuda-atomic-add-fallback.h
  include/ceed/jit-source/cuda/cuda-gen-templates.h
  include/ceed/jit-source/cuda/cuda-ref-operator-assemble-diagonal.h
  include/ceed/jit-source/cuda/cuda-ref-restriction-curl-oriented.h
  include/ceed/jit-source/cuda/cuda-ref-restriction-offset.h
  include/ceed/jit-source/cuda/cuda-ref-restriction-oriented.h
  include/ceed/jit-source/cuda/cuda-ref-restriction-strided.h
  include/ceed/jit-source/cuda/cuda-ref-restriction.h
  include/ceed/jit-source/hip/hip-gen-templates.h
  include/ceed/jit-source/hip/hip-ref-operator-assemble-diagonal.h
  include/ceed/jit-source/hip/hip-ref-restriction-curl-oriented.h
  include/ceed/jit-source/hip/hip-ref-restriction-offset.h
  include/ceed/jit-source/hip/hip-ref-restriction-oriented.h
  include/ceed/jit-source/hip/hip-ref-restriction-strided.h
  include/ceed/jit-source/hip/hip-ref-restriction.h
  include/ceed/jit-source/sycl/sycl-gen-templates.h
Labels: GPU, performance, 1-In Review

#1452 fluids: Stats don't overwrite solution on first-step failure
  examples/fluids/src/turb_spanstats.c
Labels: examples, 1-In Review

#1436 Add deal.II example
  .gitlab-ci.yml
  Makefile
  examples/deal.II/.clang-format
  examples/deal.II/.gitignore
  examples/deal.II/CMakeLists.txt
  examples/deal.II/README.MD
  examples/deal.II/bps-qfunctions.h
  examples/deal.II/bps.cc
  examples/deal.II/bps.h
  tests/junit.py
  tests/junit_common.py
Labels: examples, 1-In Review

#1459 Add deal.II to release notes
  doc/sphinx/source/releasenotes.md
  examples/deal.II/bps.h
Labels: minor, documentation, 1-In Review
