Repository CEED/libCEED, pull requests merged in 2024-12, with the labels that each got.

#1713 test: Update diff_csv to process commented lines
  tests/junit_common.py
Labels: enhancement, testing, 1-In Review

#1711 GPU Shared AtPoints Bases
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/hip-shared/ceed-hip-shared-basis.c
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-at-points-templates.h
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-at-points.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-at-points-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-at-points.h
  interface/ceed-preconditioning.c
  tests/t354-basis.c
Labels: enhancement, CUDA, 1-In Review, HIP

#1714 Fix FLOPs estimates AtPoints
  include/ceed/backend.h
  interface/ceed-basis.c
  interface/ceed-operator.c
  tests/t595-operator.c
  tests/t595-operator.h
Labels: enhancement, minor, 1-In Review

#1716 Gen AtPoints Updates
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  include/ceed/backend.h
  include/ceed/jit-source/cuda/cuda-gen-templates.h
  include/ceed/jit-source/cuda/cuda-shared-basis-read-write-templates.h
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-at-points-templates.h
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-at-points.h
  include/ceed/jit-source/hip/hip-gen-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-read-write-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-at-points-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-at-points.h
Labels: minor, GPU, 1-In Review
