Repository CEED/libCEED, pull requests merged in 2025-04, with the labels that each got.

#1801 actions - use latest gcc
  .github/workflows/c-fortan-test-ppc64le.yml
  .github/workflows/c-fortran-test-arm64.yml
  .github/workflows/c-fortran-test-linux-osx.yml
  .github/workflows/c-fortran-test-style.yml
  .github/workflows/python-test-with-style.yml
  .github/workflows/rust-test-with-style.yml
Labels: 1-In Review, CI

#1800 Fix edge case in offset padding for empty cells
  backends/cuda-ref/ceed-cuda-ref-restriction.c
  backends/hip-ref/ceed-hip-ref-restriction.c
Labels: bug, backend, 1-In Review

#1807 op - minor at points diagonal improvements
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/ref/ceed-ref-operator.c
Labels: GPU, performance, CPU, 1-In Review

#1810 gen - unload module when destroying op
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-shared/ceed-cuda-shared.h
  backends/hip-gen/ceed-hip-gen-operator.c
Labels: bug, GPU, CUDA, 1-In Review, HIP

#1799 AtPoints assembly for CPU
  backends/ref/ceed-ref-operator.c
  interface/ceed-preconditioning.c
  tests/t596-operator.c
  tests/t596-operator.h
  tests/t597-operator.c
  tests/t597-operator.h
Labels: enhancement, CPU, 1-In Review

#1809 Add fallback compiler settings equivalent to gcc default
  Makefile
Labels: building, 1-In Review

#1812 Reset work vectors in operator setup to save memory
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/hip-ref/ceed-hip-ref-operator.c
  include/ceed/backend.h
  interface/ceed.c
  tests/t131-vector.c
Labels: GPU

#1814 pc - multigrid level setup for AtPoints
  interface/ceed-preconditioning.c
  tests/t598-operator.c
Labels: interface, 1-In Review
