Repository CEED/libCEED, pull requests merged in 2025-07, with the labels that each got.

#1851 GPU Gen QFunction Assembly
  backends/cuda-gen/ceed-cuda-gen-operator-build.cpp
  backends/cuda-gen/ceed-cuda-gen-operator-build.h
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-gen/ceed-cuda-gen.h
  backends/cuda/ceed-cuda-compile.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.cpp
  backends/hip-gen/ceed-hip-gen-operator-build.h
  backends/hip-gen/ceed-hip-gen-operator.c
  backends/hip-gen/ceed-hip-gen.h
  backends/hip/ceed-hip-compile.cpp
  include/ceed/backend.h
  include/ceed/jit-source/cuda/cuda-gen-templates.h
  include/ceed/jit-source/hip/hip-gen-templates.h
  interface/ceed-preconditioning.c
  interface/ceed-qfunction-register.c
  interface/ceed-register.c
  interface/ceed.c
  tests/t531-operator.c
Labels: GPU, CUDA, 0-WIP, HIP

#1852 basis - fix flop counting for gpu at-points
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-at-points-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-at-points-templates.h
  interface/ceed-basis.c
Labels: bug, GPU, 1-In Review

#1855 Fix grad basis flop counts
  interface/ceed-basis.c
Labels: bug, 1-In Review

#1861 op - Add `CeedOperatorApplyAddActive()` for only summing into active outputs
  include/ceed/ceed.h
  interface/ceed-operator.c
Labels: interface, 1-In Review

#1863 AtPoints Tuning
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-at-points-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-at-points-templates.h
Labels: GPU, performance, 1-In Review

#1864 deal.II Example Updates
  examples/deal.II/bps.h
Labels: examples, 1-In Review, deal.II

#1866 gpu - fix gen AtPoints transpose
  include/ceed/jit-source/cuda/cuda-shared-basis-tensor-at-points-templates.h
  include/ceed/jit-source/hip/hip-shared-basis-tensor-at-points-templates.h
Labels: bug, GPU, 1-In Review

#1867 Bypass strange lcov error
  .gitlab-ci.yml
Labels: bug, 1-In Review, CI

#1868 Pull BasisIsCollocated helper to interface level
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref.h
  include/ceed/backend.h
  interface/ceed-basis.c
Labels: minor, interface, 1-In Review

#1871 ci - add default test name (file name)
  tests/junit_common.py
Labels: 1-In Review, CI

#1872 ci - update junit_common with changes from HONEE
  tests/junit_common.py
Labels: 1-In Review, CI

#1874 dealii - use /cpu/self as default
  examples/deal.II/bps.cc
Labels: examples, CPU, 1-In Review, deal.II
