Repository CEED/libCEED, pull requests merged in 2025-09, with the labels that each got.

#1890 at-points - ensure reference point coordinates are always up to date
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/cuda-ref/ceed-cuda-ref.h
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/hip-ref/ceed-hip-ref.h
Labels: backend, CUDA, 1-In Review, HIP

#1894 deprecated.h: fix typo
  include/ceed/deprecated.h
Labels: minor

#1896 style: Change clang-format to penalize newline after open ()
  .clang-format
  backends/blocked/ceed-blocked-operator.c
  backends/cuda-gen/ceed-cuda-gen-operator.c
  backends/cuda-ref/ceed-cuda-ref-basis.c
  backends/cuda-ref/ceed-cuda-ref-operator.c
  backends/cuda-ref/ceed-cuda-ref-restriction.c
  backends/cuda-shared/ceed-cuda-shared-basis.c
  backends/cuda/ceed-cuda-compile.cpp
  backends/hip-gen/ceed-hip-gen-operator.c
  backends/hip-ref/ceed-hip-ref-basis.c
  backends/hip-ref/ceed-hip-ref-operator.c
  backends/hip-ref/ceed-hip-ref-restriction.c
  backends/hip-shared/ceed-hip-shared-basis.c
  backends/memcheck/ceed-memcheck-restriction.c
  backends/opt/ceed-opt-operator.c
  backends/ref/ceed-ref-basis.c
  backends/ref/ceed-ref-operator.c
  backends/ref/ceed-ref-restriction.c
  backends/sycl-ref/ceed-sycl-ref-operator.sycl.cpp
  backends/sycl/ceed-sycl-compile.sycl.cpp
  examples/fluids/problems/advection.c
  examples/fluids/problems/bc_freestream.c
  examples/fluids/problems/blasius.c
  examples/fluids/src/differential_filter.c
  examples/fluids/src/dm_utils.c
  examples/fluids/src/misc.c
  examples/fluids/src/setupts.c
  examples/fluids/src/turb_spanstats.c
  examples/fluids/src/velocity_gradient_projection.c
  examples/petsc/bpsraw.c
  examples/petsc/dmswarm.c
  examples/solids/src/cl-options.c
  examples/solids/src/setup-libceed.c
  interface/ceed-elemrestriction.c
  interface/ceed-preconditioning.c
Labels: minor, 1-In Review, style
